# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Preconditions
#'
#' Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
#' @name V1Preconditions
#' @noMd
#' @export
V1Preconditions <- R6::R6Class(
  "V1Preconditions",
  public = list(
    `resource_version` = NULL,
    `uid` = NULL
    ,
    #' @description Construct.
    initialize = function(`resource_version` = NULL, `uid` = NULL) {
      self$`resource_version` <- `resource_version`
      self$`uid` <- `uid`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["resourceVersion"]] <- self$`resource_version`
      out[["uid"]] <- self$`uid`
      drop_nulls_deep(out)
    }
  )
)

V1Preconditions$from_list <- function(x) {
  V1Preconditions$new(
    `resource_version` = x[["resourceVersion"]],
    `uid` = x[["uid"]]
  )
}

