# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1beta1SelfSubjectReviewStatus
#'
#' SelfSubjectReviewStatus is filled by the kube-apiserver and sent back to a user.
#' @name V1beta1SelfSubjectReviewStatus
#' @noMd
#' @export
V1beta1SelfSubjectReviewStatus <- R6::R6Class(
  "V1beta1SelfSubjectReviewStatus",
  public = list(
    `user_info` = NULL
    ,
    #' @description Construct.
    initialize = function(`user_info` = NULL) {
      self$`user_info` <- `user_info`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["userInfo"]] <- if (!is.null(self$`user_info`)) self$`user_info`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1beta1SelfSubjectReviewStatus$from_list <- function(x) {
  V1beta1SelfSubjectReviewStatus$new(
    `user_info` = if (is.null(x[["userInfo"]])) NULL else V1UserInfo$from_list(x[["userInfo"]])
  )
}

