# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CustomResourceDefinitionNames
#'
#' CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition
#' @name V1CustomResourceDefinitionNames
#' @noMd
#' @export
V1CustomResourceDefinitionNames <- R6::R6Class(
  "V1CustomResourceDefinitionNames",
  public = list(
    `categories` = NULL,
    `kind` = NULL,
    `list_kind` = NULL,
    `plural` = NULL,
    `short_names` = NULL,
    `singular` = NULL
    ,
    #' @description Construct.
    initialize = function(`categories` = NULL, `kind` = NULL, `list_kind` = NULL, `plural` = NULL, `short_names` = NULL, `singular` = NULL) {
      self$`categories` <- `categories`
      self$`kind` <- `kind`
      self$`list_kind` <- `list_kind`
      self$`plural` <- `plural`
      self$`short_names` <- `short_names`
      self$`singular` <- `singular`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["categories"]] <- self$`categories`
      out[["kind"]] <- self$`kind`
      out[["listKind"]] <- self$`list_kind`
      out[["plural"]] <- self$`plural`
      out[["shortNames"]] <- self$`short_names`
      out[["singular"]] <- self$`singular`
      drop_nulls_deep(out)
    }
  )
)

V1CustomResourceDefinitionNames$from_list <- function(x) {
  V1CustomResourceDefinitionNames$new(
    `categories` = x[["categories"]],
    `kind` = x[["kind"]],
    `list_kind` = x[["listKind"]],
    `plural` = x[["plural"]],
    `short_names` = x[["shortNames"]],
    `singular` = x[["singular"]]
  )
}

V1CustomResourceDefinitionNames$required_fields <- c("plural", "kind")

