# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CSIPersistentVolumeSource
#'
#' Represents storage that is managed by an external CSI volume driver (Beta feature)
#' @name V1CSIPersistentVolumeSource
#' @noMd
#' @export
V1CSIPersistentVolumeSource <- R6::R6Class(
  "V1CSIPersistentVolumeSource",
  public = list(
    `controller_expand_secret_ref` = NULL,
    `controller_publish_secret_ref` = NULL,
    `driver` = NULL,
    `fs_type` = NULL,
    `node_expand_secret_ref` = NULL,
    `node_publish_secret_ref` = NULL,
    `node_stage_secret_ref` = NULL,
    `read_only` = NULL,
    `volume_attributes` = NULL,
    `volume_handle` = NULL
    ,
    #' @description Construct.
    initialize = function(`controller_expand_secret_ref` = NULL, `controller_publish_secret_ref` = NULL, `driver` = NULL, `fs_type` = NULL, `node_expand_secret_ref` = NULL, `node_publish_secret_ref` = NULL, `node_stage_secret_ref` = NULL, `read_only` = NULL, `volume_attributes` = NULL, `volume_handle` = NULL) {
      self$`controller_expand_secret_ref` <- `controller_expand_secret_ref`
      self$`controller_publish_secret_ref` <- `controller_publish_secret_ref`
      self$`driver` <- `driver`
      self$`fs_type` <- `fs_type`
      self$`node_expand_secret_ref` <- `node_expand_secret_ref`
      self$`node_publish_secret_ref` <- `node_publish_secret_ref`
      self$`node_stage_secret_ref` <- `node_stage_secret_ref`
      self$`read_only` <- `read_only`
      self$`volume_attributes` <- `volume_attributes`
      self$`volume_handle` <- `volume_handle`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["controllerExpandSecretRef"]] <- if (!is.null(self$`controller_expand_secret_ref`)) self$`controller_expand_secret_ref`$to_list() else NULL
      out[["controllerPublishSecretRef"]] <- if (!is.null(self$`controller_publish_secret_ref`)) self$`controller_publish_secret_ref`$to_list() else NULL
      out[["driver"]] <- self$`driver`
      out[["fsType"]] <- self$`fs_type`
      out[["nodeExpandSecretRef"]] <- if (!is.null(self$`node_expand_secret_ref`)) self$`node_expand_secret_ref`$to_list() else NULL
      out[["nodePublishSecretRef"]] <- if (!is.null(self$`node_publish_secret_ref`)) self$`node_publish_secret_ref`$to_list() else NULL
      out[["nodeStageSecretRef"]] <- if (!is.null(self$`node_stage_secret_ref`)) self$`node_stage_secret_ref`$to_list() else NULL
      out[["readOnly"]] <- self$`read_only`
      out[["volumeAttributes"]] <- self$`volume_attributes`
      out[["volumeHandle"]] <- self$`volume_handle`
      drop_nulls_deep(out)
    }
  )
)

V1CSIPersistentVolumeSource$from_list <- function(x) {
  V1CSIPersistentVolumeSource$new(
    `controller_expand_secret_ref` = if (is.null(x[["controllerExpandSecretRef"]])) NULL else V1SecretReference$from_list(x[["controllerExpandSecretRef"]]),
    `controller_publish_secret_ref` = if (is.null(x[["controllerPublishSecretRef"]])) NULL else V1SecretReference$from_list(x[["controllerPublishSecretRef"]]),
    `driver` = x[["driver"]],
    `fs_type` = x[["fsType"]],
    `node_expand_secret_ref` = if (is.null(x[["nodeExpandSecretRef"]])) NULL else V1SecretReference$from_list(x[["nodeExpandSecretRef"]]),
    `node_publish_secret_ref` = if (is.null(x[["nodePublishSecretRef"]])) NULL else V1SecretReference$from_list(x[["nodePublishSecretRef"]]),
    `node_stage_secret_ref` = if (is.null(x[["nodeStageSecretRef"]])) NULL else V1SecretReference$from_list(x[["nodeStageSecretRef"]]),
    `read_only` = x[["readOnly"]],
    `volume_attributes` = x[["volumeAttributes"]],
    `volume_handle` = x[["volumeHandle"]]
  )
}

V1CSIPersistentVolumeSource$required_fields <- c("driver", "volumeHandle")

