# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NodeRuntimeHandlerFeatures
#'
#' NodeRuntimeHandlerFeatures is a set of features implemented by the runtime handler.
#' @name V1NodeRuntimeHandlerFeatures
#' @noMd
#' @export
V1NodeRuntimeHandlerFeatures <- R6::R6Class(
  "V1NodeRuntimeHandlerFeatures",
  public = list(
    `recursive_read_only_mounts` = NULL,
    `user_namespaces` = NULL
    ,
    #' @description Construct.
    initialize = function(`recursive_read_only_mounts` = NULL, `user_namespaces` = NULL) {
      self$`recursive_read_only_mounts` <- `recursive_read_only_mounts`
      self$`user_namespaces` <- `user_namespaces`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["recursiveReadOnlyMounts"]] <- self$`recursive_read_only_mounts`
      out[["userNamespaces"]] <- self$`user_namespaces`
      drop_nulls_deep(out)
    }
  )
)

V1NodeRuntimeHandlerFeatures$from_list <- function(x) {
  V1NodeRuntimeHandlerFeatures$new(
    `recursive_read_only_mounts` = x[["recursiveReadOnlyMounts"]],
    `user_namespaces` = x[["userNamespaces"]]
  )
}

