# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1DeploymentStatus
#'
#' DeploymentStatus is the most recently observed status of the Deployment.
#' @name V1DeploymentStatus
#' @noMd
#' @export
V1DeploymentStatus <- R6::R6Class(
  "V1DeploymentStatus",
  public = list(
    `available_replicas` = NULL,
    `collision_count` = NULL,
    `conditions` = NULL,
    `observed_generation` = NULL,
    `ready_replicas` = NULL,
    `replicas` = NULL,
    `unavailable_replicas` = NULL,
    `updated_replicas` = NULL
    ,
    #' @description Construct.
    initialize = function(`available_replicas` = NULL, `collision_count` = NULL, `conditions` = NULL, `observed_generation` = NULL, `ready_replicas` = NULL, `replicas` = NULL, `unavailable_replicas` = NULL, `updated_replicas` = NULL) {
      self$`available_replicas` <- `available_replicas`
      self$`collision_count` <- `collision_count`
      self$`conditions` <- `conditions`
      self$`observed_generation` <- `observed_generation`
      self$`ready_replicas` <- `ready_replicas`
      self$`replicas` <- `replicas`
      self$`unavailable_replicas` <- `unavailable_replicas`
      self$`updated_replicas` <- `updated_replicas`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["availableReplicas"]] <- self$`available_replicas`
      out[["collisionCount"]] <- self$`collision_count`
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["observedGeneration"]] <- self$`observed_generation`
      out[["readyReplicas"]] <- self$`ready_replicas`
      out[["replicas"]] <- self$`replicas`
      out[["unavailableReplicas"]] <- self$`unavailable_replicas`
      out[["updatedReplicas"]] <- self$`updated_replicas`
      drop_nulls_deep(out)
    }
  )
)

V1DeploymentStatus$from_list <- function(x) {
  V1DeploymentStatus$new(
    `available_replicas` = x[["availableReplicas"]],
    `collision_count` = x[["collisionCount"]],
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1DeploymentCondition$from_list),
    `observed_generation` = x[["observedGeneration"]],
    `ready_replicas` = x[["readyReplicas"]],
    `replicas` = x[["replicas"]],
    `unavailable_replicas` = x[["unavailableReplicas"]],
    `updated_replicas` = x[["updatedReplicas"]]
  )
}

