# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Endpoint
#'
#' Endpoint represents a single logical "backend" implementing a service.
#' @name V1Endpoint
#' @noMd
#' @export
V1Endpoint <- R6::R6Class(
  "V1Endpoint",
  public = list(
    `addresses` = NULL,
    `conditions` = NULL,
    `deprecated_topology` = NULL,
    `hints` = NULL,
    `hostname` = NULL,
    `node_name` = NULL,
    `target_ref` = NULL,
    `zone` = NULL
    ,
    #' @description Construct.
    initialize = function(`addresses` = NULL, `conditions` = NULL, `deprecated_topology` = NULL, `hints` = NULL, `hostname` = NULL, `node_name` = NULL, `target_ref` = NULL, `zone` = NULL) {
      self$`addresses` <- `addresses`
      self$`conditions` <- `conditions`
      self$`deprecated_topology` <- `deprecated_topology`
      self$`hints` <- `hints`
      self$`hostname` <- `hostname`
      self$`node_name` <- `node_name`
      self$`target_ref` <- `target_ref`
      self$`zone` <- `zone`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["addresses"]] <- self$`addresses`
      out[["conditions"]] <- if (!is.null(self$`conditions`)) self$`conditions`$to_list() else NULL
      out[["deprecatedTopology"]] <- self$`deprecated_topology`
      out[["hints"]] <- if (!is.null(self$`hints`)) self$`hints`$to_list() else NULL
      out[["hostname"]] <- self$`hostname`
      out[["nodeName"]] <- self$`node_name`
      out[["targetRef"]] <- if (!is.null(self$`target_ref`)) self$`target_ref`$to_list() else NULL
      out[["zone"]] <- self$`zone`
      drop_nulls_deep(out)
    }
  )
)

V1Endpoint$from_list <- function(x) {
  V1Endpoint$new(
    `addresses` = x[["addresses"]],
    `conditions` = if (is.null(x[["conditions"]])) NULL else V1EndpointConditions$from_list(x[["conditions"]]),
    `deprecated_topology` = x[["deprecatedTopology"]],
    `hints` = if (is.null(x[["hints"]])) NULL else V1EndpointHints$from_list(x[["hints"]]),
    `hostname` = x[["hostname"]],
    `node_name` = x[["nodeName"]],
    `target_ref` = if (is.null(x[["targetRef"]])) NULL else V1ObjectReference$from_list(x[["targetRef"]]),
    `zone` = x[["zone"]]
  )
}

V1Endpoint$required_fields <- c("addresses")

