# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CustomResourceValidation
#'
#' CustomResourceValidation is a list of validation methods for CustomResources.
#' @name V1CustomResourceValidation
#' @noMd
#' @export
V1CustomResourceValidation <- R6::R6Class(
  "V1CustomResourceValidation",
  public = list(
    `open_apiv3_schema` = NULL
    ,
    #' @description Construct.
    initialize = function(`open_apiv3_schema` = NULL) {
      self$`open_apiv3_schema` <- `open_apiv3_schema`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["openAPIV3Schema"]] <- if (!is.null(self$`open_apiv3_schema`)) self$`open_apiv3_schema`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1CustomResourceValidation$from_list <- function(x) {
  V1CustomResourceValidation$new(
    `open_apiv3_schema` = if (is.null(x[["openAPIV3Schema"]])) NULL else V1JSONSchemaProps$from_list(x[["openAPIV3Schema"]])
  )
}

