# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1beta1Variable
#'
#' Variable is the definition of a variable that is used for composition. A variable is defined as a named expression.
#' @name V1beta1Variable
#' @noMd
#' @export
V1beta1Variable <- R6::R6Class(
  "V1beta1Variable",
  public = list(
    `expression` = NULL,
    `name` = NULL
    ,
    #' @description Construct.
    initialize = function(`expression` = NULL, `name` = NULL) {
      self$`expression` <- `expression`
      self$`name` <- `name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["expression"]] <- self$`expression`
      out[["name"]] <- self$`name`
      drop_nulls_deep(out)
    }
  )
)

V1beta1Variable$from_list <- function(x) {
  V1beta1Variable$new(
    `expression` = x[["expression"]],
    `name` = x[["name"]]
  )
}

V1beta1Variable$required_fields <- c("name", "expression")

