# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NonResourcePolicyRule
#'
#' NonResourcePolicyRule is a predicate that matches non-resource requests according to their verb and the target non-resource URL. A NonResourcePolicyRule matches a request if and only if both (a) at least one member of verbs matches the request and (b) at least one member of nonResourceURLs matches the request.
#' @name V1NonResourcePolicyRule
#' @noMd
#' @export
V1NonResourcePolicyRule <- R6::R6Class(
  "V1NonResourcePolicyRule",
  public = list(
    `non_resource_ur_ls` = NULL,
    `verbs` = NULL
    ,
    #' @description Construct.
    initialize = function(`non_resource_ur_ls` = NULL, `verbs` = NULL) {
      self$`non_resource_ur_ls` <- `non_resource_ur_ls`
      self$`verbs` <- `verbs`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["nonResourceURLs"]] <- self$`non_resource_ur_ls`
      out[["verbs"]] <- self$`verbs`
      drop_nulls_deep(out)
    }
  )
)

V1NonResourcePolicyRule$from_list <- function(x) {
  V1NonResourcePolicyRule$new(
    `non_resource_ur_ls` = x[["nonResourceURLs"]],
    `verbs` = x[["verbs"]]
  )
}

V1NonResourcePolicyRule$required_fields <- c("verbs", "nonResourceURLs")

