# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1LifecycleHandler
#'
#' LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
#' @name V1LifecycleHandler
#' @noMd
#' @export
V1LifecycleHandler <- R6::R6Class(
  "V1LifecycleHandler",
  public = list(
    `exec` = NULL,
    `http_get` = NULL,
    `sleep` = NULL,
    `tcp_socket` = NULL
    ,
    #' @description Construct.
    initialize = function(`exec` = NULL, `http_get` = NULL, `sleep` = NULL, `tcp_socket` = NULL) {
      self$`exec` <- `exec`
      self$`http_get` <- `http_get`
      self$`sleep` <- `sleep`
      self$`tcp_socket` <- `tcp_socket`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["exec"]] <- if (!is.null(self$`exec`)) self$`exec`$to_list() else NULL
      out[["httpGet"]] <- if (!is.null(self$`http_get`)) self$`http_get`$to_list() else NULL
      out[["sleep"]] <- if (!is.null(self$`sleep`)) self$`sleep`$to_list() else NULL
      out[["tcpSocket"]] <- if (!is.null(self$`tcp_socket`)) self$`tcp_socket`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1LifecycleHandler$from_list <- function(x) {
  V1LifecycleHandler$new(
    `exec` = if (is.null(x[["exec"]])) NULL else V1ExecAction$from_list(x[["exec"]]),
    `http_get` = if (is.null(x[["httpGet"]])) NULL else V1HTTPGetAction$from_list(x[["httpGet"]]),
    `sleep` = if (is.null(x[["sleep"]])) NULL else V1SleepAction$from_list(x[["sleep"]]),
    `tcp_socket` = if (is.null(x[["tcpSocket"]])) NULL else V1TCPSocketAction$from_list(x[["tcpSocket"]])
  )
}

