# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ContainerState
#'
#' ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.
#' @name V1ContainerState
#' @noMd
#' @export
V1ContainerState <- R6::R6Class(
  "V1ContainerState",
  public = list(
    `running` = NULL,
    `terminated` = NULL,
    `waiting` = NULL
    ,
    #' @description Construct.
    initialize = function(`running` = NULL, `terminated` = NULL, `waiting` = NULL) {
      self$`running` <- `running`
      self$`terminated` <- `terminated`
      self$`waiting` <- `waiting`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["running"]] <- if (!is.null(self$`running`)) self$`running`$to_list() else NULL
      out[["terminated"]] <- if (!is.null(self$`terminated`)) self$`terminated`$to_list() else NULL
      out[["waiting"]] <- if (!is.null(self$`waiting`)) self$`waiting`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ContainerState$from_list <- function(x) {
  V1ContainerState$new(
    `running` = if (is.null(x[["running"]])) NULL else V1ContainerStateRunning$from_list(x[["running"]]),
    `terminated` = if (is.null(x[["terminated"]])) NULL else V1ContainerStateTerminated$from_list(x[["terminated"]]),
    `waiting` = if (is.null(x[["waiting"]])) NULL else V1ContainerStateWaiting$from_list(x[["waiting"]])
  )
}

