# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha1StorageVersionSpec
#'
#' StorageVersionSpec is an empty spec.
#' @name V1alpha1StorageVersionSpec
#' @noMd
#' @export
V1alpha1StorageVersionSpec <- R6::R6Class(
  "V1alpha1StorageVersionSpec",
  public = list(
    #' @field value Underlying scalar / unstructured value.
    value = NULL,
    #' @description Construct.
    #' @param value The underlying value.
    initialize = function(value = NULL) { self$value <- value },
    #' @description Return the underlying value (no key wrapping).
    to_list = function() self$value
  )
)

V1alpha1StorageVersionSpec$from_list <- function(x) V1alpha1StorageVersionSpec$new(value = x)

