# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ValidatingAdmissionPolicyBindingList
#'
#' ValidatingAdmissionPolicyBindingList is a list of ValidatingAdmissionPolicyBinding.
#' @name V1ValidatingAdmissionPolicyBindingList
#' @noMd
#' @export
V1ValidatingAdmissionPolicyBindingList <- R6::R6Class(
  "V1ValidatingAdmissionPolicyBindingList",
  public = list(
    `api_version` = NULL,
    `items` = NULL,
    `kind` = NULL,
    `metadata` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `items` = NULL, `kind` = NULL, `metadata` = NULL) {
      self$`api_version` <- `api_version`
      self$`items` <- `items`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["items"]] <- if (!is.null(self$`items`)) lapply(self$`items`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ValidatingAdmissionPolicyBindingList$from_list <- function(x) {
  V1ValidatingAdmissionPolicyBindingList$new(
    `api_version` = x[["apiVersion"]],
    `items` = if (is.null(x[["items"]])) NULL else lapply(x[["items"]], V1ValidatingAdmissionPolicyBinding$from_list),
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ListMeta$from_list(x[["metadata"]])
  )
}

V1ValidatingAdmissionPolicyBindingList$required_fields <- c("items")

