# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1StatefulSetSpec
#'
#' A StatefulSetSpec is the specification of a StatefulSet.
#' @name V1StatefulSetSpec
#' @noMd
#' @export
V1StatefulSetSpec <- R6::R6Class(
  "V1StatefulSetSpec",
  public = list(
    `min_ready_seconds` = NULL,
    `ordinals` = NULL,
    `persistent_volume_claim_retention_policy` = NULL,
    `pod_management_policy` = NULL,
    `replicas` = NULL,
    `revision_history_limit` = NULL,
    `selector` = NULL,
    `service_name` = NULL,
    `template` = NULL,
    `update_strategy` = NULL,
    `volume_claim_templates` = NULL
    ,
    #' @description Construct.
    initialize = function(`min_ready_seconds` = NULL, `ordinals` = NULL, `persistent_volume_claim_retention_policy` = NULL, `pod_management_policy` = NULL, `replicas` = NULL, `revision_history_limit` = NULL, `selector` = NULL, `service_name` = NULL, `template` = NULL, `update_strategy` = NULL, `volume_claim_templates` = NULL) {
      self$`min_ready_seconds` <- `min_ready_seconds`
      self$`ordinals` <- `ordinals`
      self$`persistent_volume_claim_retention_policy` <- `persistent_volume_claim_retention_policy`
      self$`pod_management_policy` <- `pod_management_policy`
      self$`replicas` <- `replicas`
      self$`revision_history_limit` <- `revision_history_limit`
      self$`selector` <- `selector`
      self$`service_name` <- `service_name`
      self$`template` <- `template`
      self$`update_strategy` <- `update_strategy`
      self$`volume_claim_templates` <- `volume_claim_templates`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["minReadySeconds"]] <- self$`min_ready_seconds`
      out[["ordinals"]] <- if (!is.null(self$`ordinals`)) self$`ordinals`$to_list() else NULL
      out[["persistentVolumeClaimRetentionPolicy"]] <- if (!is.null(self$`persistent_volume_claim_retention_policy`)) self$`persistent_volume_claim_retention_policy`$to_list() else NULL
      out[["podManagementPolicy"]] <- self$`pod_management_policy`
      out[["replicas"]] <- self$`replicas`
      out[["revisionHistoryLimit"]] <- self$`revision_history_limit`
      out[["selector"]] <- if (!is.null(self$`selector`)) self$`selector`$to_list() else NULL
      out[["serviceName"]] <- self$`service_name`
      out[["template"]] <- if (!is.null(self$`template`)) self$`template`$to_list() else NULL
      out[["updateStrategy"]] <- if (!is.null(self$`update_strategy`)) self$`update_strategy`$to_list() else NULL
      out[["volumeClaimTemplates"]] <- if (!is.null(self$`volume_claim_templates`)) lapply(self$`volume_claim_templates`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1StatefulSetSpec$from_list <- function(x) {
  V1StatefulSetSpec$new(
    `min_ready_seconds` = x[["minReadySeconds"]],
    `ordinals` = if (is.null(x[["ordinals"]])) NULL else V1StatefulSetOrdinals$from_list(x[["ordinals"]]),
    `persistent_volume_claim_retention_policy` = if (is.null(x[["persistentVolumeClaimRetentionPolicy"]])) NULL else V1StatefulSetPersistentVolumeClaimRetentionPolicy$from_list(x[["persistentVolumeClaimRetentionPolicy"]]),
    `pod_management_policy` = x[["podManagementPolicy"]],
    `replicas` = x[["replicas"]],
    `revision_history_limit` = x[["revisionHistoryLimit"]],
    `selector` = if (is.null(x[["selector"]])) NULL else V1LabelSelector$from_list(x[["selector"]]),
    `service_name` = x[["serviceName"]],
    `template` = if (is.null(x[["template"]])) NULL else V1PodTemplateSpec$from_list(x[["template"]]),
    `update_strategy` = if (is.null(x[["updateStrategy"]])) NULL else V1StatefulSetUpdateStrategy$from_list(x[["updateStrategy"]]),
    `volume_claim_templates` = if (is.null(x[["volumeClaimTemplates"]])) NULL else lapply(x[["volumeClaimTemplates"]], V1PersistentVolumeClaim$from_list)
  )
}

V1StatefulSetSpec$required_fields <- c("selector", "template", "serviceName")

