# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1LocalObjectReference
#'
#' LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
#' @name V1LocalObjectReference
#' @noMd
#' @export
V1LocalObjectReference <- R6::R6Class(
  "V1LocalObjectReference",
  public = list(
    `name` = NULL
    ,
    #' @description Construct.
    initialize = function(`name` = NULL) {
      self$`name` <- `name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["name"]] <- self$`name`
      drop_nulls_deep(out)
    }
  )
)

V1LocalObjectReference$from_list <- function(x) {
  V1LocalObjectReference$new(
    `name` = x[["name"]]
  )
}

