# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Status
#'
#' Status is a return value for calls that don't return other objects.
#' @name V1Status
#' @noMd
#' @export
V1Status <- R6::R6Class(
  "V1Status",
  public = list(
    `api_version` = NULL,
    `code` = NULL,
    `details` = NULL,
    `kind` = NULL,
    `message` = NULL,
    `metadata` = NULL,
    `reason` = NULL,
    `status` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `code` = NULL, `details` = NULL, `kind` = NULL, `message` = NULL, `metadata` = NULL, `reason` = NULL, `status` = NULL) {
      self$`api_version` <- `api_version`
      self$`code` <- `code`
      self$`details` <- `details`
      self$`kind` <- `kind`
      self$`message` <- `message`
      self$`metadata` <- `metadata`
      self$`reason` <- `reason`
      self$`status` <- `status`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["code"]] <- self$`code`
      out[["details"]] <- if (!is.null(self$`details`)) self$`details`$to_list() else NULL
      out[["kind"]] <- self$`kind`
      out[["message"]] <- self$`message`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["reason"]] <- self$`reason`
      out[["status"]] <- self$`status`
      drop_nulls_deep(out)
    }
  )
)

V1Status$from_list <- function(x) {
  V1Status$new(
    `api_version` = x[["apiVersion"]],
    `code` = x[["code"]],
    `details` = if (is.null(x[["details"]])) NULL else V1StatusDetails$from_list(x[["details"]]),
    `kind` = x[["kind"]],
    `message` = x[["message"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ListMeta$from_list(x[["metadata"]]),
    `reason` = x[["reason"]],
    `status` = x[["status"]]
  )
}

