# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1IngressRule
#'
#' IngressRule represents the rules mapping the paths under a specified host to the related backend services. Incoming requests are first evaluated for a host match, then routed to the backend associated with the matching IngressRuleValue.
#' @name V1IngressRule
#' @noMd
#' @export
V1IngressRule <- R6::R6Class(
  "V1IngressRule",
  public = list(
    `host` = NULL,
    `http` = NULL
    ,
    #' @description Construct.
    initialize = function(`host` = NULL, `http` = NULL) {
      self$`host` <- `host`
      self$`http` <- `http`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["host"]] <- self$`host`
      out[["http"]] <- if (!is.null(self$`http`)) self$`http`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1IngressRule$from_list <- function(x) {
  V1IngressRule$new(
    `host` = x[["host"]],
    `http` = if (is.null(x[["http"]])) NULL else V1HTTPIngressRuleValue$from_list(x[["http"]])
  )
}

