# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1FlowSchemaStatus
#'
#' FlowSchemaStatus represents the current state of a FlowSchema.
#' @name V1FlowSchemaStatus
#' @noMd
#' @export
V1FlowSchemaStatus <- R6::R6Class(
  "V1FlowSchemaStatus",
  public = list(
    `conditions` = NULL
    ,
    #' @description Construct.
    initialize = function(`conditions` = NULL) {
      self$`conditions` <- `conditions`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1FlowSchemaStatus$from_list <- function(x) {
  V1FlowSchemaStatus$new(
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1FlowSchemaCondition$from_list)
  )
}

