# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1VolumeError
#'
#' VolumeError captures an error encountered during a volume operation.
#' @name V1VolumeError
#' @noMd
#' @export
V1VolumeError <- R6::R6Class(
  "V1VolumeError",
  public = list(
    `message` = NULL,
    `time` = NULL
    ,
    #' @description Construct.
    initialize = function(`message` = NULL, `time` = NULL) {
      self$`message` <- `message`
      self$`time` <- `time`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["message"]] <- self$`message`
      out[["time"]] <- if (!is.null(self$`time`)) self$`time`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1VolumeError$from_list <- function(x) {
  V1VolumeError$new(
    `message` = x[["message"]],
    `time` = if (is.null(x[["time"]])) NULL else V1Time$from_list(x[["time"]])
  )
}

