# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ServiceStatus
#'
#' ServiceStatus represents the current status of a service.
#' @name V1ServiceStatus
#' @noMd
#' @export
V1ServiceStatus <- R6::R6Class(
  "V1ServiceStatus",
  public = list(
    `conditions` = NULL,
    `load_balancer` = NULL
    ,
    #' @description Construct.
    initialize = function(`conditions` = NULL, `load_balancer` = NULL) {
      self$`conditions` <- `conditions`
      self$`load_balancer` <- `load_balancer`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["loadBalancer"]] <- if (!is.null(self$`load_balancer`)) self$`load_balancer`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ServiceStatus$from_list <- function(x) {
  V1ServiceStatus$new(
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1Condition$from_list),
    `load_balancer` = if (is.null(x[["loadBalancer"]])) NULL else V1LoadBalancerStatus$from_list(x[["loadBalancer"]])
  )
}

