# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1VsphereVirtualDiskVolumeSource
#'
#' Represents a vSphere volume resource.
#' @name V1VsphereVirtualDiskVolumeSource
#' @noMd
#' @export
V1VsphereVirtualDiskVolumeSource <- R6::R6Class(
  "V1VsphereVirtualDiskVolumeSource",
  public = list(
    `fs_type` = NULL,
    `storage_policy_id` = NULL,
    `storage_policy_name` = NULL,
    `volume_path` = NULL
    ,
    #' @description Construct.
    initialize = function(`fs_type` = NULL, `storage_policy_id` = NULL, `storage_policy_name` = NULL, `volume_path` = NULL) {
      self$`fs_type` <- `fs_type`
      self$`storage_policy_id` <- `storage_policy_id`
      self$`storage_policy_name` <- `storage_policy_name`
      self$`volume_path` <- `volume_path`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["fsType"]] <- self$`fs_type`
      out[["storagePolicyID"]] <- self$`storage_policy_id`
      out[["storagePolicyName"]] <- self$`storage_policy_name`
      out[["volumePath"]] <- self$`volume_path`
      drop_nulls_deep(out)
    }
  )
)

V1VsphereVirtualDiskVolumeSource$from_list <- function(x) {
  V1VsphereVirtualDiskVolumeSource$new(
    `fs_type` = x[["fsType"]],
    `storage_policy_id` = x[["storagePolicyID"]],
    `storage_policy_name` = x[["storagePolicyName"]],
    `volume_path` = x[["volumePath"]]
  )
}

V1VsphereVirtualDiskVolumeSource$required_fields <- c("volumePath")

