# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3CELDeviceSelector
#'
#' CELDeviceSelector contains a CEL expression for selecting a device.
#' @name V1alpha3CELDeviceSelector
#' @noMd
#' @export
V1alpha3CELDeviceSelector <- R6::R6Class(
  "V1alpha3CELDeviceSelector",
  public = list(
    `expression` = NULL
    ,
    #' @description Construct.
    initialize = function(`expression` = NULL) {
      self$`expression` <- `expression`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["expression"]] <- self$`expression`
      drop_nulls_deep(out)
    }
  )
)

V1alpha3CELDeviceSelector$from_list <- function(x) {
  V1alpha3CELDeviceSelector$new(
    `expression` = x[["expression"]]
  )
}

V1alpha3CELDeviceSelector$required_fields <- c("expression")

