# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Volume
#'
#' Volume represents a named volume in a pod that may be accessed by any container in the pod.
#' @name V1Volume
#' @noMd
#' @export
V1Volume <- R6::R6Class(
  "V1Volume",
  public = list(
    `aws_elastic_block_store` = NULL,
    `azure_disk` = NULL,
    `azure_file` = NULL,
    `cephfs` = NULL,
    `cinder` = NULL,
    `config_map` = NULL,
    `csi` = NULL,
    `downward_api` = NULL,
    `empty_dir` = NULL,
    `ephemeral` = NULL,
    `fc` = NULL,
    `flex_volume` = NULL,
    `flocker` = NULL,
    `gce_persistent_disk` = NULL,
    `git_repo` = NULL,
    `glusterfs` = NULL,
    `host_path` = NULL,
    `image` = NULL,
    `iscsi` = NULL,
    `name` = NULL,
    `nfs` = NULL,
    `persistent_volume_claim` = NULL,
    `photon_persistent_disk` = NULL,
    `portworx_volume` = NULL,
    `projected` = NULL,
    `quobyte` = NULL,
    `rbd` = NULL,
    `scale_io` = NULL,
    `secret` = NULL,
    `storageos` = NULL,
    `vsphere_volume` = NULL
    ,
    #' @description Construct.
    initialize = function(`aws_elastic_block_store` = NULL, `azure_disk` = NULL, `azure_file` = NULL, `cephfs` = NULL, `cinder` = NULL, `config_map` = NULL, `csi` = NULL, `downward_api` = NULL, `empty_dir` = NULL, `ephemeral` = NULL, `fc` = NULL, `flex_volume` = NULL, `flocker` = NULL, `gce_persistent_disk` = NULL, `git_repo` = NULL, `glusterfs` = NULL, `host_path` = NULL, `image` = NULL, `iscsi` = NULL, `name` = NULL, `nfs` = NULL, `persistent_volume_claim` = NULL, `photon_persistent_disk` = NULL, `portworx_volume` = NULL, `projected` = NULL, `quobyte` = NULL, `rbd` = NULL, `scale_io` = NULL, `secret` = NULL, `storageos` = NULL, `vsphere_volume` = NULL) {
      self$`aws_elastic_block_store` <- `aws_elastic_block_store`
      self$`azure_disk` <- `azure_disk`
      self$`azure_file` <- `azure_file`
      self$`cephfs` <- `cephfs`
      self$`cinder` <- `cinder`
      self$`config_map` <- `config_map`
      self$`csi` <- `csi`
      self$`downward_api` <- `downward_api`
      self$`empty_dir` <- `empty_dir`
      self$`ephemeral` <- `ephemeral`
      self$`fc` <- `fc`
      self$`flex_volume` <- `flex_volume`
      self$`flocker` <- `flocker`
      self$`gce_persistent_disk` <- `gce_persistent_disk`
      self$`git_repo` <- `git_repo`
      self$`glusterfs` <- `glusterfs`
      self$`host_path` <- `host_path`
      self$`image` <- `image`
      self$`iscsi` <- `iscsi`
      self$`name` <- `name`
      self$`nfs` <- `nfs`
      self$`persistent_volume_claim` <- `persistent_volume_claim`
      self$`photon_persistent_disk` <- `photon_persistent_disk`
      self$`portworx_volume` <- `portworx_volume`
      self$`projected` <- `projected`
      self$`quobyte` <- `quobyte`
      self$`rbd` <- `rbd`
      self$`scale_io` <- `scale_io`
      self$`secret` <- `secret`
      self$`storageos` <- `storageos`
      self$`vsphere_volume` <- `vsphere_volume`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["awsElasticBlockStore"]] <- if (!is.null(self$`aws_elastic_block_store`)) self$`aws_elastic_block_store`$to_list() else NULL
      out[["azureDisk"]] <- if (!is.null(self$`azure_disk`)) self$`azure_disk`$to_list() else NULL
      out[["azureFile"]] <- if (!is.null(self$`azure_file`)) self$`azure_file`$to_list() else NULL
      out[["cephfs"]] <- if (!is.null(self$`cephfs`)) self$`cephfs`$to_list() else NULL
      out[["cinder"]] <- if (!is.null(self$`cinder`)) self$`cinder`$to_list() else NULL
      out[["configMap"]] <- if (!is.null(self$`config_map`)) self$`config_map`$to_list() else NULL
      out[["csi"]] <- if (!is.null(self$`csi`)) self$`csi`$to_list() else NULL
      out[["downwardAPI"]] <- if (!is.null(self$`downward_api`)) self$`downward_api`$to_list() else NULL
      out[["emptyDir"]] <- if (!is.null(self$`empty_dir`)) self$`empty_dir`$to_list() else NULL
      out[["ephemeral"]] <- if (!is.null(self$`ephemeral`)) self$`ephemeral`$to_list() else NULL
      out[["fc"]] <- if (!is.null(self$`fc`)) self$`fc`$to_list() else NULL
      out[["flexVolume"]] <- if (!is.null(self$`flex_volume`)) self$`flex_volume`$to_list() else NULL
      out[["flocker"]] <- if (!is.null(self$`flocker`)) self$`flocker`$to_list() else NULL
      out[["gcePersistentDisk"]] <- if (!is.null(self$`gce_persistent_disk`)) self$`gce_persistent_disk`$to_list() else NULL
      out[["gitRepo"]] <- if (!is.null(self$`git_repo`)) self$`git_repo`$to_list() else NULL
      out[["glusterfs"]] <- if (!is.null(self$`glusterfs`)) self$`glusterfs`$to_list() else NULL
      out[["hostPath"]] <- if (!is.null(self$`host_path`)) self$`host_path`$to_list() else NULL
      out[["image"]] <- if (!is.null(self$`image`)) self$`image`$to_list() else NULL
      out[["iscsi"]] <- if (!is.null(self$`iscsi`)) self$`iscsi`$to_list() else NULL
      out[["name"]] <- self$`name`
      out[["nfs"]] <- if (!is.null(self$`nfs`)) self$`nfs`$to_list() else NULL
      out[["persistentVolumeClaim"]] <- if (!is.null(self$`persistent_volume_claim`)) self$`persistent_volume_claim`$to_list() else NULL
      out[["photonPersistentDisk"]] <- if (!is.null(self$`photon_persistent_disk`)) self$`photon_persistent_disk`$to_list() else NULL
      out[["portworxVolume"]] <- if (!is.null(self$`portworx_volume`)) self$`portworx_volume`$to_list() else NULL
      out[["projected"]] <- if (!is.null(self$`projected`)) self$`projected`$to_list() else NULL
      out[["quobyte"]] <- if (!is.null(self$`quobyte`)) self$`quobyte`$to_list() else NULL
      out[["rbd"]] <- if (!is.null(self$`rbd`)) self$`rbd`$to_list() else NULL
      out[["scaleIO"]] <- if (!is.null(self$`scale_io`)) self$`scale_io`$to_list() else NULL
      out[["secret"]] <- if (!is.null(self$`secret`)) self$`secret`$to_list() else NULL
      out[["storageos"]] <- if (!is.null(self$`storageos`)) self$`storageos`$to_list() else NULL
      out[["vsphereVolume"]] <- if (!is.null(self$`vsphere_volume`)) self$`vsphere_volume`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1Volume$from_list <- function(x) {
  V1Volume$new(
    `aws_elastic_block_store` = if (is.null(x[["awsElasticBlockStore"]])) NULL else V1AWSElasticBlockStoreVolumeSource$from_list(x[["awsElasticBlockStore"]]),
    `azure_disk` = if (is.null(x[["azureDisk"]])) NULL else V1AzureDiskVolumeSource$from_list(x[["azureDisk"]]),
    `azure_file` = if (is.null(x[["azureFile"]])) NULL else V1AzureFileVolumeSource$from_list(x[["azureFile"]]),
    `cephfs` = if (is.null(x[["cephfs"]])) NULL else V1CephFSVolumeSource$from_list(x[["cephfs"]]),
    `cinder` = if (is.null(x[["cinder"]])) NULL else V1CinderVolumeSource$from_list(x[["cinder"]]),
    `config_map` = if (is.null(x[["configMap"]])) NULL else V1ConfigMapVolumeSource$from_list(x[["configMap"]]),
    `csi` = if (is.null(x[["csi"]])) NULL else V1CSIVolumeSource$from_list(x[["csi"]]),
    `downward_api` = if (is.null(x[["downwardAPI"]])) NULL else V1DownwardAPIVolumeSource$from_list(x[["downwardAPI"]]),
    `empty_dir` = if (is.null(x[["emptyDir"]])) NULL else V1EmptyDirVolumeSource$from_list(x[["emptyDir"]]),
    `ephemeral` = if (is.null(x[["ephemeral"]])) NULL else V1EphemeralVolumeSource$from_list(x[["ephemeral"]]),
    `fc` = if (is.null(x[["fc"]])) NULL else V1FCVolumeSource$from_list(x[["fc"]]),
    `flex_volume` = if (is.null(x[["flexVolume"]])) NULL else V1FlexVolumeSource$from_list(x[["flexVolume"]]),
    `flocker` = if (is.null(x[["flocker"]])) NULL else V1FlockerVolumeSource$from_list(x[["flocker"]]),
    `gce_persistent_disk` = if (is.null(x[["gcePersistentDisk"]])) NULL else V1GCEPersistentDiskVolumeSource$from_list(x[["gcePersistentDisk"]]),
    `git_repo` = if (is.null(x[["gitRepo"]])) NULL else V1GitRepoVolumeSource$from_list(x[["gitRepo"]]),
    `glusterfs` = if (is.null(x[["glusterfs"]])) NULL else V1GlusterfsVolumeSource$from_list(x[["glusterfs"]]),
    `host_path` = if (is.null(x[["hostPath"]])) NULL else V1HostPathVolumeSource$from_list(x[["hostPath"]]),
    `image` = if (is.null(x[["image"]])) NULL else V1ImageVolumeSource$from_list(x[["image"]]),
    `iscsi` = if (is.null(x[["iscsi"]])) NULL else V1ISCSIVolumeSource$from_list(x[["iscsi"]]),
    `name` = x[["name"]],
    `nfs` = if (is.null(x[["nfs"]])) NULL else V1NFSVolumeSource$from_list(x[["nfs"]]),
    `persistent_volume_claim` = if (is.null(x[["persistentVolumeClaim"]])) NULL else V1PersistentVolumeClaimVolumeSource$from_list(x[["persistentVolumeClaim"]]),
    `photon_persistent_disk` = if (is.null(x[["photonPersistentDisk"]])) NULL else V1PhotonPersistentDiskVolumeSource$from_list(x[["photonPersistentDisk"]]),
    `portworx_volume` = if (is.null(x[["portworxVolume"]])) NULL else V1PortworxVolumeSource$from_list(x[["portworxVolume"]]),
    `projected` = if (is.null(x[["projected"]])) NULL else V1ProjectedVolumeSource$from_list(x[["projected"]]),
    `quobyte` = if (is.null(x[["quobyte"]])) NULL else V1QuobyteVolumeSource$from_list(x[["quobyte"]]),
    `rbd` = if (is.null(x[["rbd"]])) NULL else V1RBDVolumeSource$from_list(x[["rbd"]]),
    `scale_io` = if (is.null(x[["scaleIO"]])) NULL else V1ScaleIOVolumeSource$from_list(x[["scaleIO"]]),
    `secret` = if (is.null(x[["secret"]])) NULL else V1SecretVolumeSource$from_list(x[["secret"]]),
    `storageos` = if (is.null(x[["storageos"]])) NULL else V1StorageOSVolumeSource$from_list(x[["storageos"]]),
    `vsphere_volume` = if (is.null(x[["vsphereVolume"]])) NULL else V1VsphereVirtualDiskVolumeSource$from_list(x[["vsphereVolume"]])
  )
}

V1Volume$required_fields <- c("name")

