# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1TokenReviewStatus
#'
#' TokenReviewStatus is the result of the token authentication request.
#' @name V1TokenReviewStatus
#' @noMd
#' @export
V1TokenReviewStatus <- R6::R6Class(
  "V1TokenReviewStatus",
  public = list(
    `audiences` = NULL,
    `authenticated` = NULL,
    `error` = NULL,
    `user` = NULL
    ,
    #' @description Construct.
    initialize = function(`audiences` = NULL, `authenticated` = NULL, `error` = NULL, `user` = NULL) {
      self$`audiences` <- `audiences`
      self$`authenticated` <- `authenticated`
      self$`error` <- `error`
      self$`user` <- `user`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["audiences"]] <- self$`audiences`
      out[["authenticated"]] <- self$`authenticated`
      out[["error"]] <- self$`error`
      out[["user"]] <- if (!is.null(self$`user`)) self$`user`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1TokenReviewStatus$from_list <- function(x) {
  V1TokenReviewStatus$new(
    `audiences` = x[["audiences"]],
    `authenticated` = x[["authenticated"]],
    `error` = x[["error"]],
    `user` = if (is.null(x[["user"]])) NULL else V1UserInfo$from_list(x[["user"]])
  )
}

