# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ResourceClaim
#'
#' ResourceClaim references one entry in PodSpec.ResourceClaims.
#' @name V1ResourceClaim
#' @noMd
#' @export
V1ResourceClaim <- R6::R6Class(
  "V1ResourceClaim",
  public = list(
    `name` = NULL,
    `request` = NULL
    ,
    #' @description Construct.
    initialize = function(`name` = NULL, `request` = NULL) {
      self$`name` <- `name`
      self$`request` <- `request`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["name"]] <- self$`name`
      out[["request"]] <- self$`request`
      drop_nulls_deep(out)
    }
  )
)

V1ResourceClaim$from_list <- function(x) {
  V1ResourceClaim$new(
    `name` = x[["name"]],
    `request` = x[["request"]]
  )
}

V1ResourceClaim$required_fields <- c("name")

