# Generated by tools/gen/generate.R -- do not edit by hand.

#' CertificatesV1Api
#'
#' Typed Kubernetes API client for the `CertificatesV1` surface. See generated methods for available operations.
#' @name CertificatesV1Api
#' @noMd
#' @export
CertificatesV1Api <- R6::R6Class(
  "CertificatesV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getCertificatesV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listCertificatesV1CertificateSigningRequest
    #' list or watch objects of kind CertificateSigningRequest
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_certificate_signing_request = function(pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests",
        method = "GET",
        path_params = list(),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1CertificateSigningRequestList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createCertificatesV1CertificateSigningRequest
    #' create a CertificateSigningRequest
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_certificate_signing_request = function(body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests",
        method = "POST",
        path_params = list(),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteCertificatesV1CollectionCertificateSigningRequest
    #' delete collection of CertificateSigningRequest
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_certificate_signing_request = function(pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests",
        method = "DELETE",
        path_params = list(),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readCertificatesV1CertificateSigningRequest
    #' read the specified CertificateSigningRequest
    #' @param name
    #' @param pretty = NULL
    read_certificate_signing_request = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceCertificatesV1CertificateSigningRequest
    #' replace the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_certificate_signing_request = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchCertificatesV1CertificateSigningRequest
    #' partially update the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_certificate_signing_request = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteCertificatesV1CertificateSigningRequest
    #' delete a CertificateSigningRequest
    #' @param name
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_certificate_signing_request = function(name, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readCertificatesV1CertificateSigningRequestApproval
    #' read approval of the specified CertificateSigningRequest
    #' @param name
    #' @param pretty = NULL
    read_certificate_signing_request_approval = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/approval",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceCertificatesV1CertificateSigningRequestApproval
    #' replace approval of the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_certificate_signing_request_approval = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/approval",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchCertificatesV1CertificateSigningRequestApproval
    #' partially update approval of the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_certificate_signing_request_approval = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/approval",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' readCertificatesV1CertificateSigningRequestStatus
    #' read status of the specified CertificateSigningRequest
    #' @param name
    #' @param pretty = NULL
    read_certificate_signing_request_status = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/status",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceCertificatesV1CertificateSigningRequestStatus
    #' replace status of the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_certificate_signing_request_status = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/status",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchCertificatesV1CertificateSigningRequestStatus
    #' partially update status of the specified CertificateSigningRequest
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_certificate_signing_request_status = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/certificatesigningrequests/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CertificateSigningRequest",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' watchCertificatesV1CertificateSigningRequestList
    #' watch individual changes to a list of CertificateSigningRequest. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_certificate_signing_request_list = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/watch/certificatesigningrequests",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCertificatesV1CertificateSigningRequest
    #' watch changes to an object of kind CertificateSigningRequest. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_certificate_signing_request = function(name, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1/watch/certificatesigningrequests/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

