# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1IngressClassParametersReference
#'
#' IngressClassParametersReference identifies an API object. This can be used to specify a cluster or namespace-scoped resource.
#' @name V1IngressClassParametersReference
#' @noMd
#' @export
V1IngressClassParametersReference <- R6::R6Class(
  "V1IngressClassParametersReference",
  public = list(
    `api_group` = NULL,
    `kind` = NULL,
    `name` = NULL,
    `namespace` = NULL,
    `scope` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_group` = NULL, `kind` = NULL, `name` = NULL, `namespace` = NULL, `scope` = NULL) {
      self$`api_group` <- `api_group`
      self$`kind` <- `kind`
      self$`name` <- `name`
      self$`namespace` <- `namespace`
      self$`scope` <- `scope`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiGroup"]] <- self$`api_group`
      out[["kind"]] <- self$`kind`
      out[["name"]] <- self$`name`
      out[["namespace"]] <- self$`namespace`
      out[["scope"]] <- self$`scope`
      drop_nulls_deep(out)
    }
  )
)

V1IngressClassParametersReference$from_list <- function(x) {
  V1IngressClassParametersReference$new(
    `api_group` = x[["apiGroup"]],
    `kind` = x[["kind"]],
    `name` = x[["name"]],
    `namespace` = x[["namespace"]],
    `scope` = x[["scope"]]
  )
}

V1IngressClassParametersReference$required_fields <- c("kind", "name")

