# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ReplicationControllerStatus
#'
#' ReplicationControllerStatus represents the current status of a replication controller.
#' @name V1ReplicationControllerStatus
#' @noMd
#' @export
V1ReplicationControllerStatus <- R6::R6Class(
  "V1ReplicationControllerStatus",
  public = list(
    `available_replicas` = NULL,
    `conditions` = NULL,
    `fully_labeled_replicas` = NULL,
    `observed_generation` = NULL,
    `ready_replicas` = NULL,
    `replicas` = NULL
    ,
    #' @description Construct.
    initialize = function(`available_replicas` = NULL, `conditions` = NULL, `fully_labeled_replicas` = NULL, `observed_generation` = NULL, `ready_replicas` = NULL, `replicas` = NULL) {
      self$`available_replicas` <- `available_replicas`
      self$`conditions` <- `conditions`
      self$`fully_labeled_replicas` <- `fully_labeled_replicas`
      self$`observed_generation` <- `observed_generation`
      self$`ready_replicas` <- `ready_replicas`
      self$`replicas` <- `replicas`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["availableReplicas"]] <- self$`available_replicas`
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["fullyLabeledReplicas"]] <- self$`fully_labeled_replicas`
      out[["observedGeneration"]] <- self$`observed_generation`
      out[["readyReplicas"]] <- self$`ready_replicas`
      out[["replicas"]] <- self$`replicas`
      drop_nulls_deep(out)
    }
  )
)

V1ReplicationControllerStatus$from_list <- function(x) {
  V1ReplicationControllerStatus$new(
    `available_replicas` = x[["availableReplicas"]],
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1ReplicationControllerCondition$from_list),
    `fully_labeled_replicas` = x[["fullyLabeledReplicas"]],
    `observed_generation` = x[["observedGeneration"]],
    `ready_replicas` = x[["readyReplicas"]],
    `replicas` = x[["replicas"]]
  )
}

V1ReplicationControllerStatus$required_fields <- c("replicas")

