# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1DeploymentCondition
#'
#' DeploymentCondition describes the state of a deployment at a certain point.
#' @name V1DeploymentCondition
#' @noMd
#' @export
V1DeploymentCondition <- R6::R6Class(
  "V1DeploymentCondition",
  public = list(
    `last_transition_time` = NULL,
    `last_update_time` = NULL,
    `message` = NULL,
    `reason` = NULL,
    `status` = NULL,
    `type` = NULL
    ,
    #' @description Construct.
    initialize = function(`last_transition_time` = NULL, `last_update_time` = NULL, `message` = NULL, `reason` = NULL, `status` = NULL, `type` = NULL) {
      self$`last_transition_time` <- `last_transition_time`
      self$`last_update_time` <- `last_update_time`
      self$`message` <- `message`
      self$`reason` <- `reason`
      self$`status` <- `status`
      self$`type` <- `type`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["lastTransitionTime"]] <- if (!is.null(self$`last_transition_time`)) self$`last_transition_time`$to_list() else NULL
      out[["lastUpdateTime"]] <- if (!is.null(self$`last_update_time`)) self$`last_update_time`$to_list() else NULL
      out[["message"]] <- self$`message`
      out[["reason"]] <- self$`reason`
      out[["status"]] <- self$`status`
      out[["type"]] <- self$`type`
      drop_nulls_deep(out)
    }
  )
)

V1DeploymentCondition$from_list <- function(x) {
  V1DeploymentCondition$new(
    `last_transition_time` = if (is.null(x[["lastTransitionTime"]])) NULL else V1Time$from_list(x[["lastTransitionTime"]]),
    `last_update_time` = if (is.null(x[["lastUpdateTime"]])) NULL else V1Time$from_list(x[["lastUpdateTime"]]),
    `message` = x[["message"]],
    `reason` = x[["reason"]],
    `status` = x[["status"]],
    `type` = x[["type"]]
  )
}

V1DeploymentCondition$required_fields <- c("type", "status")

