# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha1ValidatingAdmissionPolicyBindingSpec
#'
#' ValidatingAdmissionPolicyBindingSpec is the specification of the ValidatingAdmissionPolicyBinding.
#' @name V1alpha1ValidatingAdmissionPolicyBindingSpec
#' @noMd
#' @export
V1alpha1ValidatingAdmissionPolicyBindingSpec <- R6::R6Class(
  "V1alpha1ValidatingAdmissionPolicyBindingSpec",
  public = list(
    `match_resources` = NULL,
    `param_ref` = NULL,
    `policy_name` = NULL,
    `validation_actions` = NULL
    ,
    #' @description Construct.
    initialize = function(`match_resources` = NULL, `param_ref` = NULL, `policy_name` = NULL, `validation_actions` = NULL) {
      self$`match_resources` <- `match_resources`
      self$`param_ref` <- `param_ref`
      self$`policy_name` <- `policy_name`
      self$`validation_actions` <- `validation_actions`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["matchResources"]] <- if (!is.null(self$`match_resources`)) self$`match_resources`$to_list() else NULL
      out[["paramRef"]] <- if (!is.null(self$`param_ref`)) self$`param_ref`$to_list() else NULL
      out[["policyName"]] <- self$`policy_name`
      out[["validationActions"]] <- self$`validation_actions`
      drop_nulls_deep(out)
    }
  )
)

V1alpha1ValidatingAdmissionPolicyBindingSpec$from_list <- function(x) {
  V1alpha1ValidatingAdmissionPolicyBindingSpec$new(
    `match_resources` = if (is.null(x[["matchResources"]])) NULL else V1alpha1MatchResources$from_list(x[["matchResources"]]),
    `param_ref` = if (is.null(x[["paramRef"]])) NULL else V1alpha1ParamRef$from_list(x[["paramRef"]]),
    `policy_name` = x[["policyName"]],
    `validation_actions` = x[["validationActions"]]
  )
}

