# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ValidatingWebhookConfiguration
#'
#' ValidatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and object without changing it.
#' @name V1ValidatingWebhookConfiguration
#' @noMd
#' @export
V1ValidatingWebhookConfiguration <- R6::R6Class(
  "V1ValidatingWebhookConfiguration",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `webhooks` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `webhooks` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`webhooks` <- `webhooks`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["webhooks"]] <- if (!is.null(self$`webhooks`)) lapply(self$`webhooks`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ValidatingWebhookConfiguration$from_list <- function(x) {
  V1ValidatingWebhookConfiguration$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `webhooks` = if (is.null(x[["webhooks"]])) NULL else lapply(x[["webhooks"]], V1ValidatingWebhook$from_list)
  )
}

