# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NodeRuntimeHandler
#'
#' NodeRuntimeHandler is a set of runtime handler information.
#' @name V1NodeRuntimeHandler
#' @noMd
#' @export
V1NodeRuntimeHandler <- R6::R6Class(
  "V1NodeRuntimeHandler",
  public = list(
    `features` = NULL,
    `name` = NULL
    ,
    #' @description Construct.
    initialize = function(`features` = NULL, `name` = NULL) {
      self$`features` <- `features`
      self$`name` <- `name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["features"]] <- if (!is.null(self$`features`)) self$`features`$to_list() else NULL
      out[["name"]] <- self$`name`
      drop_nulls_deep(out)
    }
  )
)

V1NodeRuntimeHandler$from_list <- function(x) {
  V1NodeRuntimeHandler$new(
    `features` = if (is.null(x[["features"]])) NULL else V1NodeRuntimeHandlerFeatures$from_list(x[["features"]]),
    `name` = x[["name"]]
  )
}

