# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ConfigMapKeySelector
#'
#' Selects a key from a ConfigMap.
#' @name V1ConfigMapKeySelector
#' @noMd
#' @export
V1ConfigMapKeySelector <- R6::R6Class(
  "V1ConfigMapKeySelector",
  public = list(
    `key` = NULL,
    `name` = NULL,
    `optional` = NULL
    ,
    #' @description Construct.
    initialize = function(`key` = NULL, `name` = NULL, `optional` = NULL) {
      self$`key` <- `key`
      self$`name` <- `name`
      self$`optional` <- `optional`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["key"]] <- self$`key`
      out[["name"]] <- self$`name`
      out[["optional"]] <- self$`optional`
      drop_nulls_deep(out)
    }
  )
)

V1ConfigMapKeySelector$from_list <- function(x) {
  V1ConfigMapKeySelector$new(
    `key` = x[["key"]],
    `name` = x[["name"]],
    `optional` = x[["optional"]]
  )
}

V1ConfigMapKeySelector$required_fields <- c("key")

