# Generated by tools/gen/generate.R -- do not edit by hand.

#' AuthenticationV1beta1Api
#'
#' Typed Kubernetes API client for the `AuthenticationV1beta1` surface. See generated methods for available operations.
#' @name AuthenticationV1beta1Api
#' @noMd
#' @export
AuthenticationV1beta1Api <- R6::R6Class(
  "AuthenticationV1beta1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getAuthenticationV1beta1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/authentication.k8s.io/v1beta1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' createAuthenticationV1beta1SelfSubjectReview
    #' create a SelfSubjectReview
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_self_subject_review = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/authentication.k8s.io/v1beta1/selfsubjectreviews",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1beta1SelfSubjectReview",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

