# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1TypedLocalObjectReference
#'
#' TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace.
#' @name V1TypedLocalObjectReference
#' @noMd
#' @export
V1TypedLocalObjectReference <- R6::R6Class(
  "V1TypedLocalObjectReference",
  public = list(
    `api_group` = NULL,
    `kind` = NULL,
    `name` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_group` = NULL, `kind` = NULL, `name` = NULL) {
      self$`api_group` <- `api_group`
      self$`kind` <- `kind`
      self$`name` <- `name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiGroup"]] <- self$`api_group`
      out[["kind"]] <- self$`kind`
      out[["name"]] <- self$`name`
      drop_nulls_deep(out)
    }
  )
)

V1TypedLocalObjectReference$from_list <- function(x) {
  V1TypedLocalObjectReference$new(
    `api_group` = x[["apiGroup"]],
    `kind` = x[["kind"]],
    `name` = x[["name"]]
  )
}

V1TypedLocalObjectReference$required_fields <- c("kind", "name")

