# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1VolumeResourceRequirements
#'
#' VolumeResourceRequirements describes the storage resource requirements for a volume.
#' @name V1VolumeResourceRequirements
#' @noMd
#' @export
V1VolumeResourceRequirements <- R6::R6Class(
  "V1VolumeResourceRequirements",
  public = list(
    `limits` = NULL,
    `requests` = NULL
    ,
    #' @description Construct.
    initialize = function(`limits` = NULL, `requests` = NULL) {
      self$`limits` <- `limits`
      self$`requests` <- `requests`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["limits"]] <- if (!is.null(self$`limits`)) lapply(self$`limits`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["requests"]] <- if (!is.null(self$`requests`)) lapply(self$`requests`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1VolumeResourceRequirements$from_list <- function(x) {
  V1VolumeResourceRequirements$new(
    `limits` = if (is.null(x[["limits"]])) NULL else lapply(x[["limits"]], Quantity$from_list),
    `requests` = if (is.null(x[["requests"]])) NULL else lapply(x[["requests"]], Quantity$from_list)
  )
}

