# Generated by tools/gen/generate.R -- do not edit by hand.

#' AutoscalingApi
#'
#' Typed Kubernetes API client for the `Autoscaling` surface. See generated methods for available operations.
#' @name AutoscalingApi
#' @noMd
#' @export
AutoscalingApi <- R6::R6Class(
  "AutoscalingApi",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getAutoscalingAPIGroup
    #' get information of a group
    get_api_group = function() {
      self$api_client$call_api(
        resource_path = "/apis/autoscaling/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIGroup",
        content_type = "application/json",
        accept = "application/json"
      )
    }
  )
)

