# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1APIServiceStatus
#'
#' APIServiceStatus contains derived information about an API server
#' @name V1APIServiceStatus
#' @noMd
#' @export
V1APIServiceStatus <- R6::R6Class(
  "V1APIServiceStatus",
  public = list(
    `conditions` = NULL
    ,
    #' @description Construct.
    initialize = function(`conditions` = NULL) {
      self$`conditions` <- `conditions`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1APIServiceStatus$from_list <- function(x) {
  V1APIServiceStatus$new(
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1APIServiceCondition$from_list)
  )
}

