# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ScaleIOPersistentVolumeSource
#'
#' ScaleIOPersistentVolumeSource represents a persistent ScaleIO volume
#' @name V1ScaleIOPersistentVolumeSource
#' @noMd
#' @export
V1ScaleIOPersistentVolumeSource <- R6::R6Class(
  "V1ScaleIOPersistentVolumeSource",
  public = list(
    `fs_type` = NULL,
    `gateway` = NULL,
    `protection_domain` = NULL,
    `read_only` = NULL,
    `secret_ref` = NULL,
    `ssl_enabled` = NULL,
    `storage_mode` = NULL,
    `storage_pool` = NULL,
    `system` = NULL,
    `volume_name` = NULL
    ,
    #' @description Construct.
    initialize = function(`fs_type` = NULL, `gateway` = NULL, `protection_domain` = NULL, `read_only` = NULL, `secret_ref` = NULL, `ssl_enabled` = NULL, `storage_mode` = NULL, `storage_pool` = NULL, `system` = NULL, `volume_name` = NULL) {
      self$`fs_type` <- `fs_type`
      self$`gateway` <- `gateway`
      self$`protection_domain` <- `protection_domain`
      self$`read_only` <- `read_only`
      self$`secret_ref` <- `secret_ref`
      self$`ssl_enabled` <- `ssl_enabled`
      self$`storage_mode` <- `storage_mode`
      self$`storage_pool` <- `storage_pool`
      self$`system` <- `system`
      self$`volume_name` <- `volume_name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["fsType"]] <- self$`fs_type`
      out[["gateway"]] <- self$`gateway`
      out[["protectionDomain"]] <- self$`protection_domain`
      out[["readOnly"]] <- self$`read_only`
      out[["secretRef"]] <- if (!is.null(self$`secret_ref`)) self$`secret_ref`$to_list() else NULL
      out[["sslEnabled"]] <- self$`ssl_enabled`
      out[["storageMode"]] <- self$`storage_mode`
      out[["storagePool"]] <- self$`storage_pool`
      out[["system"]] <- self$`system`
      out[["volumeName"]] <- self$`volume_name`
      drop_nulls_deep(out)
    }
  )
)

V1ScaleIOPersistentVolumeSource$from_list <- function(x) {
  V1ScaleIOPersistentVolumeSource$new(
    `fs_type` = x[["fsType"]],
    `gateway` = x[["gateway"]],
    `protection_domain` = x[["protectionDomain"]],
    `read_only` = x[["readOnly"]],
    `secret_ref` = if (is.null(x[["secretRef"]])) NULL else V1SecretReference$from_list(x[["secretRef"]]),
    `ssl_enabled` = x[["sslEnabled"]],
    `storage_mode` = x[["storageMode"]],
    `storage_pool` = x[["storagePool"]],
    `system` = x[["system"]],
    `volume_name` = x[["volumeName"]]
  )
}

V1ScaleIOPersistentVolumeSource$required_fields <- c("gateway", "system", "secretRef")

