# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1PodReadinessGate
#'
#' PodReadinessGate contains the reference to a pod condition
#' @name V1PodReadinessGate
#' @noMd
#' @export
V1PodReadinessGate <- R6::R6Class(
  "V1PodReadinessGate",
  public = list(
    `condition_type` = NULL
    ,
    #' @description Construct.
    initialize = function(`condition_type` = NULL) {
      self$`condition_type` <- `condition_type`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conditionType"]] <- self$`condition_type`
      drop_nulls_deep(out)
    }
  )
)

V1PodReadinessGate$from_list <- function(x) {
  V1PodReadinessGate$new(
    `condition_type` = x[["conditionType"]]
  )
}

V1PodReadinessGate$required_fields <- c("conditionType")

