# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3DeviceRequestAllocationResult
#'
#' DeviceRequestAllocationResult contains the allocation result for one request.
#' @name V1alpha3DeviceRequestAllocationResult
#' @noMd
#' @export
V1alpha3DeviceRequestAllocationResult <- R6::R6Class(
  "V1alpha3DeviceRequestAllocationResult",
  public = list(
    `device` = NULL,
    `driver` = NULL,
    `pool` = NULL,
    `request` = NULL
    ,
    #' @description Construct.
    initialize = function(`device` = NULL, `driver` = NULL, `pool` = NULL, `request` = NULL) {
      self$`device` <- `device`
      self$`driver` <- `driver`
      self$`pool` <- `pool`
      self$`request` <- `request`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["device"]] <- self$`device`
      out[["driver"]] <- self$`driver`
      out[["pool"]] <- self$`pool`
      out[["request"]] <- self$`request`
      drop_nulls_deep(out)
    }
  )
)

V1alpha3DeviceRequestAllocationResult$from_list <- function(x) {
  V1alpha3DeviceRequestAllocationResult$new(
    `device` = x[["device"]],
    `driver` = x[["driver"]],
    `pool` = x[["pool"]],
    `request` = x[["request"]]
  )
}

V1alpha3DeviceRequestAllocationResult$required_fields <- c("request", "driver", "pool", "device")

