# Generated by tools/gen/generate.R -- do not edit by hand.

#' RbacAuthorizationV1Api
#'
#' Typed Kubernetes API client for the `RbacAuthorizationV1` surface. See generated methods for available operations.
#' @name RbacAuthorizationV1Api
#' @noMd
#' @export
RbacAuthorizationV1Api <- R6::R6Class(
  "RbacAuthorizationV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getRbacAuthorizationV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1ClusterRoleBinding
    #' list or watch objects of kind ClusterRoleBinding
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_cluster_role_binding = function(pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings",
        method = "GET",
        path_params = list(),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ClusterRoleBindingList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createRbacAuthorizationV1ClusterRoleBinding
    #' create a ClusterRoleBinding
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_cluster_role_binding = function(body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings",
        method = "POST",
        path_params = list(),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1CollectionClusterRoleBinding
    #' delete collection of ClusterRoleBinding
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_cluster_role_binding = function(pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings",
        method = "DELETE",
        path_params = list(),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readRbacAuthorizationV1ClusterRoleBinding
    #' read the specified ClusterRoleBinding
    #' @param name
    #' @param pretty = NULL
    read_cluster_role_binding = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1ClusterRoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceRbacAuthorizationV1ClusterRoleBinding
    #' replace the specified ClusterRoleBinding
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_cluster_role_binding = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchRbacAuthorizationV1ClusterRoleBinding
    #' partially update the specified ClusterRoleBinding
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_cluster_role_binding = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRoleBinding",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1ClusterRoleBinding
    #' delete a ClusterRoleBinding
    #' @param name
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_cluster_role_binding = function(name, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1ClusterRole
    #' list or watch objects of kind ClusterRole
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_cluster_role = function(pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles",
        method = "GET",
        path_params = list(),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ClusterRoleList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createRbacAuthorizationV1ClusterRole
    #' create a ClusterRole
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_cluster_role = function(body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles",
        method = "POST",
        path_params = list(),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRole",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1CollectionClusterRole
    #' delete collection of ClusterRole
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_cluster_role = function(pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles",
        method = "DELETE",
        path_params = list(),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readRbacAuthorizationV1ClusterRole
    #' read the specified ClusterRole
    #' @param name
    #' @param pretty = NULL
    read_cluster_role = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1ClusterRole",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceRbacAuthorizationV1ClusterRole
    #' replace the specified ClusterRole
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_cluster_role = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRole",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchRbacAuthorizationV1ClusterRole
    #' partially update the specified ClusterRole
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_cluster_role = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ClusterRole",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1ClusterRole
    #' delete a ClusterRole
    #' @param name
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_cluster_role = function(name, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/clusterroles/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1NamespacedRoleBinding
    #' list or watch objects of kind RoleBinding
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_role_binding = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1RoleBindingList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createRbacAuthorizationV1NamespacedRoleBinding
    #' create a RoleBinding
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_role_binding = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1RoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1CollectionNamespacedRoleBinding
    #' delete collection of RoleBinding
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_role_binding = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readRbacAuthorizationV1NamespacedRoleBinding
    #' read the specified RoleBinding
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_role_binding = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1RoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceRbacAuthorizationV1NamespacedRoleBinding
    #' replace the specified RoleBinding
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_role_binding = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1RoleBinding",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchRbacAuthorizationV1NamespacedRoleBinding
    #' partially update the specified RoleBinding
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_role_binding = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1RoleBinding",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1NamespacedRoleBinding
    #' delete a RoleBinding
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_role_binding = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1NamespacedRole
    #' list or watch objects of kind Role
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_role = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1RoleList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createRbacAuthorizationV1NamespacedRole
    #' create a Role
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_role = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Role",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1CollectionNamespacedRole
    #' delete collection of Role
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_role = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readRbacAuthorizationV1NamespacedRole
    #' read the specified Role
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_role = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Role",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceRbacAuthorizationV1NamespacedRole
    #' replace the specified Role
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_role = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Role",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchRbacAuthorizationV1NamespacedRole
    #' partially update the specified Role
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_role = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Role",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteRbacAuthorizationV1NamespacedRole
    #' delete a Role
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_role = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1RoleBindingForAllNamespaces
    #' list or watch objects of kind RoleBinding
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_role_binding_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/rolebindings",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1RoleBindingList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listRbacAuthorizationV1RoleForAllNamespaces
    #' list or watch objects of kind Role
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_role_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/roles",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1RoleList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1ClusterRoleBindingList
    #' watch individual changes to a list of ClusterRoleBinding. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_cluster_role_binding_list = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/clusterrolebindings",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1ClusterRoleBinding
    #' watch changes to an object of kind ClusterRoleBinding. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_cluster_role_binding = function(name, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/clusterrolebindings/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1ClusterRoleList
    #' watch individual changes to a list of ClusterRole. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_cluster_role_list = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/clusterroles",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1ClusterRole
    #' watch changes to an object of kind ClusterRole. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_cluster_role = function(name, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/clusterroles/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1NamespacedRoleBindingList
    #' watch individual changes to a list of RoleBinding. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_role_binding_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/namespaces/{namespace}/rolebindings",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1NamespacedRoleBinding
    #' watch changes to an object of kind RoleBinding. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_role_binding = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/namespaces/{namespace}/rolebindings/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1NamespacedRoleList
    #' watch individual changes to a list of Role. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_role_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/namespaces/{namespace}/roles",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1NamespacedRole
    #' watch changes to an object of kind Role. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_role = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/namespaces/{namespace}/roles/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1RoleBindingListForAllNamespaces
    #' watch individual changes to a list of RoleBinding. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_role_binding_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/rolebindings",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchRbacAuthorizationV1RoleListForAllNamespaces
    #' watch individual changes to a list of Role. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_role_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/rbac.authorization.k8s.io/v1/watch/roles",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

