# Generated by tools/gen/generate.R -- do not edit by hand.

#' ApiextensionsV1WebhookClientConfig
#'
#' WebhookClientConfig contains the information to make a TLS connection with the webhook.
#' @name ApiextensionsV1WebhookClientConfig
#' @noMd
#' @export
ApiextensionsV1WebhookClientConfig <- R6::R6Class(
  "ApiextensionsV1WebhookClientConfig",
  public = list(
    `ca_bundle` = NULL,
    `service` = NULL,
    `url` = NULL
    ,
    #' @description Construct.
    initialize = function(`ca_bundle` = NULL, `service` = NULL, `url` = NULL) {
      self$`ca_bundle` <- `ca_bundle`
      self$`service` <- `service`
      self$`url` <- `url`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["caBundle"]] <- self$`ca_bundle`
      out[["service"]] <- if (!is.null(self$`service`)) self$`service`$to_list() else NULL
      out[["url"]] <- self$`url`
      drop_nulls_deep(out)
    }
  )
)

ApiextensionsV1WebhookClientConfig$from_list <- function(x) {
  ApiextensionsV1WebhookClientConfig$new(
    `ca_bundle` = x[["caBundle"]],
    `service` = if (is.null(x[["service"]])) NULL else ApiextensionsV1ServiceReference$from_list(x[["service"]]),
    `url` = x[["url"]]
  )
}

