# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NodeSpec
#'
#' NodeSpec describes the attributes that a node is created with.
#' @name V1NodeSpec
#' @noMd
#' @export
V1NodeSpec <- R6::R6Class(
  "V1NodeSpec",
  public = list(
    `config_source` = NULL,
    `external_id` = NULL,
    `pod_cidr` = NULL,
    `pod_cid_rs` = NULL,
    `provider_id` = NULL,
    `taints` = NULL,
    `unschedulable` = NULL
    ,
    #' @description Construct.
    initialize = function(`config_source` = NULL, `external_id` = NULL, `pod_cidr` = NULL, `pod_cid_rs` = NULL, `provider_id` = NULL, `taints` = NULL, `unschedulable` = NULL) {
      self$`config_source` <- `config_source`
      self$`external_id` <- `external_id`
      self$`pod_cidr` <- `pod_cidr`
      self$`pod_cid_rs` <- `pod_cid_rs`
      self$`provider_id` <- `provider_id`
      self$`taints` <- `taints`
      self$`unschedulable` <- `unschedulable`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["configSource"]] <- if (!is.null(self$`config_source`)) self$`config_source`$to_list() else NULL
      out[["externalID"]] <- self$`external_id`
      out[["podCIDR"]] <- self$`pod_cidr`
      out[["podCIDRs"]] <- self$`pod_cid_rs`
      out[["providerID"]] <- self$`provider_id`
      out[["taints"]] <- if (!is.null(self$`taints`)) lapply(self$`taints`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["unschedulable"]] <- self$`unschedulable`
      drop_nulls_deep(out)
    }
  )
)

V1NodeSpec$from_list <- function(x) {
  V1NodeSpec$new(
    `config_source` = if (is.null(x[["configSource"]])) NULL else V1NodeConfigSource$from_list(x[["configSource"]]),
    `external_id` = x[["externalID"]],
    `pod_cidr` = x[["podCIDR"]],
    `pod_cid_rs` = x[["podCIDRs"]],
    `provider_id` = x[["providerID"]],
    `taints` = if (is.null(x[["taints"]])) NULL else lapply(x[["taints"]], V1Taint$from_list),
    `unschedulable` = x[["unschedulable"]]
  )
}

