# Generated by tools/gen/generate.R -- do not edit by hand.

#' StorageV1Api
#'
#' Typed Kubernetes API client for the `StorageV1` surface. See generated methods for available operations.
#' @name StorageV1Api
#' @noMd
#' @export
StorageV1Api <- R6::R6Class(
  "StorageV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getStorageV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1CSIDriver
    #' list or watch objects of kind CSIDriver
    list_csi_driver = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIDriverList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createStorageV1CSIDriver
    #' create a CSIDriver
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_csi_driver = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSIDriver",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CollectionCSIDriver
    #' delete collection of CSIDriver
    #' @param dry_run = NULL
    delete_collection_csi_driver = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1CSIDriver
    #' read the specified CSIDriver
    #' @param name
    read_csi_driver = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIDriver",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1CSIDriver
    #' replace the specified CSIDriver
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_csi_driver = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSIDriver",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1CSIDriver
    #' partially update the specified CSIDriver
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_csi_driver = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIDriver",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CSIDriver
    #' delete a CSIDriver
    #' @param name
    #' @param dry_run = NULL
    delete_csi_driver = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csidrivers/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIDriver",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1CSINode
    #' list or watch objects of kind CSINode
    list_csi_node = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSINodeList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createStorageV1CSINode
    #' create a CSINode
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_csi_node = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSINode",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CollectionCSINode
    #' delete collection of CSINode
    #' @param dry_run = NULL
    delete_collection_csi_node = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1CSINode
    #' read the specified CSINode
    #' @param name
    read_csi_node = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSINode",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1CSINode
    #' replace the specified CSINode
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_csi_node = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSINode",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1CSINode
    #' partially update the specified CSINode
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_csi_node = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1CSINode",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CSINode
    #' delete a CSINode
    #' @param name
    #' @param dry_run = NULL
    delete_csi_node = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csinodes/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1CSINode",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1CSIStorageCapacityForAllNamespaces
    #' list or watch objects of kind CSIStorageCapacity
    list_csi_storage_capacity_for_all_namespaces = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/csistoragecapacities",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIStorageCapacityList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1NamespacedCSIStorageCapacity
    #' list or watch objects of kind CSIStorageCapacity
    list_namespaced_csi_storage_capacity = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIStorageCapacityList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createStorageV1NamespacedCSIStorageCapacity
    #' create a CSIStorageCapacity
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_namespaced_csi_storage_capacity = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSIStorageCapacity",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CollectionNamespacedCSIStorageCapacity
    #' delete collection of CSIStorageCapacity
    #' @param dry_run = NULL
    delete_collection_namespaced_csi_storage_capacity = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1NamespacedCSIStorageCapacity
    #' read the specified CSIStorageCapacity
    #' @param name
    read_namespaced_csi_storage_capacity = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIStorageCapacity",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1NamespacedCSIStorageCapacity
    #' replace the specified CSIStorageCapacity
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_namespaced_csi_storage_capacity = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CSIStorageCapacity",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1NamespacedCSIStorageCapacity
    #' partially update the specified CSIStorageCapacity
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_namespaced_csi_storage_capacity = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1CSIStorageCapacity",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1NamespacedCSIStorageCapacity
    #' delete a CSIStorageCapacity
    #' @param name
    #' @param dry_run = NULL
    delete_namespaced_csi_storage_capacity = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/namespaces/{namespace}/csistoragecapacities/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1StorageClass
    #' list or watch objects of kind StorageClass
    list_storage_class = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1StorageClassList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createStorageV1StorageClass
    #' create a StorageClass
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_storage_class = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StorageClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CollectionStorageClass
    #' delete collection of StorageClass
    #' @param dry_run = NULL
    delete_collection_storage_class = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1StorageClass
    #' read the specified StorageClass
    #' @param name
    read_storage_class = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1StorageClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1StorageClass
    #' replace the specified StorageClass
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_storage_class = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StorageClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1StorageClass
    #' partially update the specified StorageClass
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_storage_class = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1StorageClass",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1StorageClass
    #' delete a StorageClass
    #' @param name
    #' @param dry_run = NULL
    delete_storage_class = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/storageclasses/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1StorageClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listStorageV1VolumeAttachment
    #' list or watch objects of kind VolumeAttachment
    list_volume_attachment = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachmentList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createStorageV1VolumeAttachment
    #' create a VolumeAttachment
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_volume_attachment = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1CollectionVolumeAttachment
    #' delete collection of VolumeAttachment
    #' @param dry_run = NULL
    delete_collection_volume_attachment = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1VolumeAttachment
    #' read the specified VolumeAttachment
    #' @param name
    read_volume_attachment = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1VolumeAttachment
    #' replace the specified VolumeAttachment
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_volume_attachment = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1VolumeAttachment
    #' partially update the specified VolumeAttachment
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_volume_attachment = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachment",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteStorageV1VolumeAttachment
    #' delete a VolumeAttachment
    #' @param name
    #' @param dry_run = NULL
    delete_volume_attachment = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readStorageV1VolumeAttachmentStatus
    #' read status of the specified VolumeAttachment
    #' @param name
    read_volume_attachment_status = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}/status",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceStorageV1VolumeAttachmentStatus
    #' replace status of the specified VolumeAttachment
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_volume_attachment_status = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}/status",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1VolumeAttachment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchStorageV1VolumeAttachmentStatus
    #' partially update status of the specified VolumeAttachment
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_volume_attachment_status = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/volumeattachments/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1VolumeAttachment",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1CSIDriverList
    #' watch individual changes to a list of CSIDriver. deprecated: use the 'watch' parameter with a list operation instead.
    watch_csi_driver_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/csidrivers",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1CSIDriver
    #' watch changes to an object of kind CSIDriver. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_csi_driver = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/csidrivers/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1CSINodeList
    #' watch individual changes to a list of CSINode. deprecated: use the 'watch' parameter with a list operation instead.
    watch_csi_node_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/csinodes",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1CSINode
    #' watch changes to an object of kind CSINode. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_csi_node = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/csinodes/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1CSIStorageCapacityListForAllNamespaces
    #' watch individual changes to a list of CSIStorageCapacity. deprecated: use the 'watch' parameter with a list operation instead.
    watch_csi_storage_capacity_list_for_all_namespaces = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/csistoragecapacities",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1NamespacedCSIStorageCapacityList
    #' watch individual changes to a list of CSIStorageCapacity. deprecated: use the 'watch' parameter with a list operation instead.
    watch_namespaced_csi_storage_capacity_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/namespaces/{namespace}/csistoragecapacities",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1NamespacedCSIStorageCapacity
    #' watch changes to an object of kind CSIStorageCapacity. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_namespaced_csi_storage_capacity = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/namespaces/{namespace}/csistoragecapacities/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1StorageClassList
    #' watch individual changes to a list of StorageClass. deprecated: use the 'watch' parameter with a list operation instead.
    watch_storage_class_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/storageclasses",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1StorageClass
    #' watch changes to an object of kind StorageClass. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_storage_class = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/storageclasses/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1VolumeAttachmentList
    #' watch individual changes to a list of VolumeAttachment. deprecated: use the 'watch' parameter with a list operation instead.
    watch_volume_attachment_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/volumeattachments",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchStorageV1VolumeAttachment
    #' watch changes to an object of kind VolumeAttachment. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_volume_attachment = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/storage.k8s.io/v1/watch/volumeattachments/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

