# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ContainerUser
#'
#' ContainerUser represents user identity information
#' @name V1ContainerUser
#' @noMd
#' @export
V1ContainerUser <- R6::R6Class(
  "V1ContainerUser",
  public = list(
    `linux` = NULL
    ,
    #' @description Construct.
    initialize = function(`linux` = NULL) {
      self$`linux` <- `linux`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["linux"]] <- if (!is.null(self$`linux`)) self$`linux`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ContainerUser$from_list <- function(x) {
  V1ContainerUser$new(
    `linux` = if (is.null(x[["linux"]])) NULL else V1LinuxContainerUser$from_list(x[["linux"]])
  )
}

