# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha1MatchCondition
#'
#' (no description)
#' @name V1alpha1MatchCondition
#' @noMd
#' @export
V1alpha1MatchCondition <- R6::R6Class(
  "V1alpha1MatchCondition",
  public = list(
    `expression` = NULL,
    `name` = NULL
    ,
    #' @description Construct.
    initialize = function(`expression` = NULL, `name` = NULL) {
      self$`expression` <- `expression`
      self$`name` <- `name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["expression"]] <- self$`expression`
      out[["name"]] <- self$`name`
      drop_nulls_deep(out)
    }
  )
)

V1alpha1MatchCondition$from_list <- function(x) {
  V1alpha1MatchCondition$new(
    `expression` = x[["expression"]],
    `name` = x[["name"]]
  )
}

V1alpha1MatchCondition$required_fields <- c("name", "expression")

