# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Ingress
#'
#' Ingress is a collection of rules that allow inbound connections to reach the endpoints defined by a backend. An Ingress can be configured to give services externally-reachable urls, load balance traffic, terminate SSL, offer name based virtual hosting etc.
#' @name V1Ingress
#' @noMd
#' @export
V1Ingress <- R6::R6Class(
  "V1Ingress",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `spec` = NULL,
    `status` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `spec` = NULL, `status` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`spec` <- `spec`
      self$`status` <- `status`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["spec"]] <- if (!is.null(self$`spec`)) self$`spec`$to_list() else NULL
      out[["status"]] <- if (!is.null(self$`status`)) self$`status`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1Ingress$from_list <- function(x) {
  V1Ingress$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `spec` = if (is.null(x[["spec"]])) NULL else V1IngressSpec$from_list(x[["spec"]]),
    `status` = if (is.null(x[["status"]])) NULL else V1IngressStatus$from_list(x[["status"]])
  )
}

