# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NamespaceSpec
#'
#' NamespaceSpec describes the attributes on a Namespace.
#' @name V1NamespaceSpec
#' @noMd
#' @export
V1NamespaceSpec <- R6::R6Class(
  "V1NamespaceSpec",
  public = list(
    `finalizers` = NULL
    ,
    #' @description Construct.
    initialize = function(`finalizers` = NULL) {
      self$`finalizers` <- `finalizers`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["finalizers"]] <- self$`finalizers`
      drop_nulls_deep(out)
    }
  )
)

V1NamespaceSpec$from_list <- function(x) {
  V1NamespaceSpec$new(
    `finalizers` = x[["finalizers"]]
  )
}

