# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1EventSource
#'
#' EventSource contains information for an event.
#' @name V1EventSource
#' @noMd
#' @export
V1EventSource <- R6::R6Class(
  "V1EventSource",
  public = list(
    `component` = NULL,
    `host` = NULL
    ,
    #' @description Construct.
    initialize = function(`component` = NULL, `host` = NULL) {
      self$`component` <- `component`
      self$`host` <- `host`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["component"]] <- self$`component`
      out[["host"]] <- self$`host`
      drop_nulls_deep(out)
    }
  )
)

V1EventSource$from_list <- function(x) {
  V1EventSource$new(
    `component` = x[["component"]],
    `host` = x[["host"]]
  )
}

