# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3BasicDevice
#'
#' BasicDevice defines one device instance.
#' @name V1alpha3BasicDevice
#' @noMd
#' @export
V1alpha3BasicDevice <- R6::R6Class(
  "V1alpha3BasicDevice",
  public = list(
    `attributes` = NULL,
    `capacity` = NULL
    ,
    #' @description Construct.
    initialize = function(`attributes` = NULL, `capacity` = NULL) {
      self$`attributes` <- `attributes`
      self$`capacity` <- `capacity`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["attributes"]] <- if (!is.null(self$`attributes`)) lapply(self$`attributes`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["capacity"]] <- if (!is.null(self$`capacity`)) lapply(self$`capacity`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1alpha3BasicDevice$from_list <- function(x) {
  V1alpha3BasicDevice$new(
    `attributes` = if (is.null(x[["attributes"]])) NULL else lapply(x[["attributes"]], V1alpha3DeviceAttribute$from_list),
    `capacity` = if (is.null(x[["capacity"]])) NULL else lapply(x[["capacity"]], Quantity$from_list)
  )
}

