# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Binding
#'
#' Binding ties one object to another; for example, a pod is bound to a node by a scheduler. Deprecated in 1.7, please use the bindings subresource of pods instead.
#' @name V1Binding
#' @noMd
#' @export
V1Binding <- R6::R6Class(
  "V1Binding",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `target` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `target` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`target` <- `target`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["target"]] <- if (!is.null(self$`target`)) self$`target`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1Binding$from_list <- function(x) {
  V1Binding$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `target` = if (is.null(x[["target"]])) NULL else V1ObjectReference$from_list(x[["target"]])
  )
}

V1Binding$required_fields <- c("target")

