# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1FlockerVolumeSource
#'
#' Represents a Flocker volume mounted by the Flocker agent. One and only one of datasetName and datasetUUID should be set. Flocker volumes do not support ownership management or SELinux relabeling.
#' @name V1FlockerVolumeSource
#' @noMd
#' @export
V1FlockerVolumeSource <- R6::R6Class(
  "V1FlockerVolumeSource",
  public = list(
    `dataset_name` = NULL,
    `dataset_uuid` = NULL
    ,
    #' @description Construct.
    initialize = function(`dataset_name` = NULL, `dataset_uuid` = NULL) {
      self$`dataset_name` <- `dataset_name`
      self$`dataset_uuid` <- `dataset_uuid`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["datasetName"]] <- self$`dataset_name`
      out[["datasetUUID"]] <- self$`dataset_uuid`
      drop_nulls_deep(out)
    }
  )
)

V1FlockerVolumeSource$from_list <- function(x) {
  V1FlockerVolumeSource$new(
    `dataset_name` = x[["datasetName"]],
    `dataset_uuid` = x[["datasetUUID"]]
  )
}

