# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1GlusterfsVolumeSource
#'
#' Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs volumes do not support ownership management or SELinux relabeling.
#' @name V1GlusterfsVolumeSource
#' @noMd
#' @export
V1GlusterfsVolumeSource <- R6::R6Class(
  "V1GlusterfsVolumeSource",
  public = list(
    `endpoints` = NULL,
    `path` = NULL,
    `read_only` = NULL
    ,
    #' @description Construct.
    initialize = function(`endpoints` = NULL, `path` = NULL, `read_only` = NULL) {
      self$`endpoints` <- `endpoints`
      self$`path` <- `path`
      self$`read_only` <- `read_only`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["endpoints"]] <- self$`endpoints`
      out[["path"]] <- self$`path`
      out[["readOnly"]] <- self$`read_only`
      drop_nulls_deep(out)
    }
  )
)

V1GlusterfsVolumeSource$from_list <- function(x) {
  V1GlusterfsVolumeSource$new(
    `endpoints` = x[["endpoints"]],
    `path` = x[["path"]],
    `read_only` = x[["readOnly"]]
  )
}

V1GlusterfsVolumeSource$required_fields <- c("endpoints", "path")

