# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1WeightedPodAffinityTerm
#'
#' The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
#' @name V1WeightedPodAffinityTerm
#' @noMd
#' @export
V1WeightedPodAffinityTerm <- R6::R6Class(
  "V1WeightedPodAffinityTerm",
  public = list(
    `pod_affinity_term` = NULL,
    `weight` = NULL
    ,
    #' @description Construct.
    initialize = function(`pod_affinity_term` = NULL, `weight` = NULL) {
      self$`pod_affinity_term` <- `pod_affinity_term`
      self$`weight` <- `weight`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["podAffinityTerm"]] <- if (!is.null(self$`pod_affinity_term`)) self$`pod_affinity_term`$to_list() else NULL
      out[["weight"]] <- self$`weight`
      drop_nulls_deep(out)
    }
  )
)

V1WeightedPodAffinityTerm$from_list <- function(x) {
  V1WeightedPodAffinityTerm$new(
    `pod_affinity_term` = if (is.null(x[["podAffinityTerm"]])) NULL else V1PodAffinityTerm$from_list(x[["podAffinityTerm"]]),
    `weight` = x[["weight"]]
  )
}

V1WeightedPodAffinityTerm$required_fields <- c("weight", "podAffinityTerm")

