# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1beta1ParentReference
#'
#' ParentReference describes a reference to a parent object.
#' @name V1beta1ParentReference
#' @noMd
#' @export
V1beta1ParentReference <- R6::R6Class(
  "V1beta1ParentReference",
  public = list(
    `group` = NULL,
    `name` = NULL,
    `namespace` = NULL,
    `resource` = NULL
    ,
    #' @description Construct.
    initialize = function(`group` = NULL, `name` = NULL, `namespace` = NULL, `resource` = NULL) {
      self$`group` <- `group`
      self$`name` <- `name`
      self$`namespace` <- `namespace`
      self$`resource` <- `resource`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["group"]] <- self$`group`
      out[["name"]] <- self$`name`
      out[["namespace"]] <- self$`namespace`
      out[["resource"]] <- self$`resource`
      drop_nulls_deep(out)
    }
  )
)

V1beta1ParentReference$from_list <- function(x) {
  V1beta1ParentReference$new(
    `group` = x[["group"]],
    `name` = x[["name"]],
    `namespace` = x[["namespace"]],
    `resource` = x[["resource"]]
  )
}

V1beta1ParentReference$required_fields <- c("resource", "name")

