# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1PodDNSConfigOption
#'
#' PodDNSConfigOption defines DNS resolver options of a pod.
#' @name V1PodDNSConfigOption
#' @noMd
#' @export
V1PodDNSConfigOption <- R6::R6Class(
  "V1PodDNSConfigOption",
  public = list(
    `name` = NULL,
    `value` = NULL
    ,
    #' @description Construct.
    initialize = function(`name` = NULL, `value` = NULL) {
      self$`name` <- `name`
      self$`value` <- `value`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["name"]] <- self$`name`
      out[["value"]] <- self$`value`
      drop_nulls_deep(out)
    }
  )
)

V1PodDNSConfigOption$from_list <- function(x) {
  V1PodDNSConfigOption$new(
    `name` = x[["name"]],
    `value` = x[["value"]]
  )
}

