# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1MutatingWebhook
#'
#' MutatingWebhook describes an admission webhook and the resources and operations it applies to.
#' @name V1MutatingWebhook
#' @noMd
#' @export
V1MutatingWebhook <- R6::R6Class(
  "V1MutatingWebhook",
  public = list(
    `admission_review_versions` = NULL,
    `client_config` = NULL,
    `failure_policy` = NULL,
    `match_conditions` = NULL,
    `match_policy` = NULL,
    `name` = NULL,
    `namespace_selector` = NULL,
    `object_selector` = NULL,
    `reinvocation_policy` = NULL,
    `rules` = NULL,
    `side_effects` = NULL,
    `timeout_seconds` = NULL
    ,
    #' @description Construct.
    initialize = function(`admission_review_versions` = NULL, `client_config` = NULL, `failure_policy` = NULL, `match_conditions` = NULL, `match_policy` = NULL, `name` = NULL, `namespace_selector` = NULL, `object_selector` = NULL, `reinvocation_policy` = NULL, `rules` = NULL, `side_effects` = NULL, `timeout_seconds` = NULL) {
      self$`admission_review_versions` <- `admission_review_versions`
      self$`client_config` <- `client_config`
      self$`failure_policy` <- `failure_policy`
      self$`match_conditions` <- `match_conditions`
      self$`match_policy` <- `match_policy`
      self$`name` <- `name`
      self$`namespace_selector` <- `namespace_selector`
      self$`object_selector` <- `object_selector`
      self$`reinvocation_policy` <- `reinvocation_policy`
      self$`rules` <- `rules`
      self$`side_effects` <- `side_effects`
      self$`timeout_seconds` <- `timeout_seconds`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["admissionReviewVersions"]] <- self$`admission_review_versions`
      out[["clientConfig"]] <- if (!is.null(self$`client_config`)) self$`client_config`$to_list() else NULL
      out[["failurePolicy"]] <- self$`failure_policy`
      out[["matchConditions"]] <- if (!is.null(self$`match_conditions`)) lapply(self$`match_conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["matchPolicy"]] <- self$`match_policy`
      out[["name"]] <- self$`name`
      out[["namespaceSelector"]] <- if (!is.null(self$`namespace_selector`)) self$`namespace_selector`$to_list() else NULL
      out[["objectSelector"]] <- if (!is.null(self$`object_selector`)) self$`object_selector`$to_list() else NULL
      out[["reinvocationPolicy"]] <- self$`reinvocation_policy`
      out[["rules"]] <- if (!is.null(self$`rules`)) lapply(self$`rules`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["sideEffects"]] <- self$`side_effects`
      out[["timeoutSeconds"]] <- self$`timeout_seconds`
      drop_nulls_deep(out)
    }
  )
)

V1MutatingWebhook$from_list <- function(x) {
  V1MutatingWebhook$new(
    `admission_review_versions` = x[["admissionReviewVersions"]],
    `client_config` = if (is.null(x[["clientConfig"]])) NULL else AdmissionregistrationV1WebhookClientConfig$from_list(x[["clientConfig"]]),
    `failure_policy` = x[["failurePolicy"]],
    `match_conditions` = if (is.null(x[["matchConditions"]])) NULL else lapply(x[["matchConditions"]], V1MatchCondition$from_list),
    `match_policy` = x[["matchPolicy"]],
    `name` = x[["name"]],
    `namespace_selector` = if (is.null(x[["namespaceSelector"]])) NULL else V1LabelSelector$from_list(x[["namespaceSelector"]]),
    `object_selector` = if (is.null(x[["objectSelector"]])) NULL else V1LabelSelector$from_list(x[["objectSelector"]]),
    `reinvocation_policy` = x[["reinvocationPolicy"]],
    `rules` = if (is.null(x[["rules"]])) NULL else lapply(x[["rules"]], V1RuleWithOperations$from_list),
    `side_effects` = x[["sideEffects"]],
    `timeout_seconds` = x[["timeoutSeconds"]]
  )
}

V1MutatingWebhook$required_fields <- c("name", "clientConfig", "sideEffects", "admissionReviewVersions")

