# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3DeviceConstraint
#'
#' DeviceConstraint must have exactly one field set besides Requests.
#' @name V1alpha3DeviceConstraint
#' @noMd
#' @export
V1alpha3DeviceConstraint <- R6::R6Class(
  "V1alpha3DeviceConstraint",
  public = list(
    `match_attribute` = NULL,
    `requests` = NULL
    ,
    #' @description Construct.
    initialize = function(`match_attribute` = NULL, `requests` = NULL) {
      self$`match_attribute` <- `match_attribute`
      self$`requests` <- `requests`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["matchAttribute"]] <- self$`match_attribute`
      out[["requests"]] <- self$`requests`
      drop_nulls_deep(out)
    }
  )
)

V1alpha3DeviceConstraint$from_list <- function(x) {
  V1alpha3DeviceConstraint$new(
    `match_attribute` = x[["matchAttribute"]],
    `requests` = x[["requests"]]
  )
}

