# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1IngressTLS
#'
#' IngressTLS describes the transport layer security associated with an ingress.
#' @name V1IngressTLS
#' @noMd
#' @export
V1IngressTLS <- R6::R6Class(
  "V1IngressTLS",
  public = list(
    `hosts` = NULL,
    `secret_name` = NULL
    ,
    #' @description Construct.
    initialize = function(`hosts` = NULL, `secret_name` = NULL) {
      self$`hosts` <- `hosts`
      self$`secret_name` <- `secret_name`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["hosts"]] <- self$`hosts`
      out[["secretName"]] <- self$`secret_name`
      drop_nulls_deep(out)
    }
  )
)

V1IngressTLS$from_list <- function(x) {
  V1IngressTLS$new(
    `hosts` = x[["hosts"]],
    `secret_name` = x[["secretName"]]
  )
}

