# Generated by tools/gen/generate.R -- do not edit by hand.

#' VersionApi
#'
#' Typed Kubernetes API client for the `Version` surface. See generated methods for available operations.
#' @name VersionApi
#' @noMd
#' @export
VersionApi <- R6::R6Class(
  "VersionApi",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getCodeVersion
    #' get the code version
    get_code_version = function() {
      self$api_client$call_api(
        resource_path = "/version/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "Info",
        content_type = "application/json",
        accept = "application/json"
      )
    }
  )
)

