# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1EndpointHints
#'
#' EndpointHints provides hints describing how an endpoint should be consumed.
#' @name V1EndpointHints
#' @noMd
#' @export
V1EndpointHints <- R6::R6Class(
  "V1EndpointHints",
  public = list(
    `for_zones` = NULL
    ,
    #' @description Construct.
    initialize = function(`for_zones` = NULL) {
      self$`for_zones` <- `for_zones`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["forZones"]] <- if (!is.null(self$`for_zones`)) lapply(self$`for_zones`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1EndpointHints$from_list <- function(x) {
  V1EndpointHints$new(
    `for_zones` = if (is.null(x[["forZones"]])) NULL else lapply(x[["forZones"]], V1ForZone$from_list)
  )
}

