# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Capabilities
#'
#' Adds and removes POSIX capabilities from running containers.
#' @name V1Capabilities
#' @noMd
#' @export
V1Capabilities <- R6::R6Class(
  "V1Capabilities",
  public = list(
    `add` = NULL,
    `drop` = NULL
    ,
    #' @description Construct.
    initialize = function(`add` = NULL, `drop` = NULL) {
      self$`add` <- `add`
      self$`drop` <- `drop`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["add"]] <- self$`add`
      out[["drop"]] <- self$`drop`
      drop_nulls_deep(out)
    }
  )
)

V1Capabilities$from_list <- function(x) {
  V1Capabilities$new(
    `add` = x[["add"]],
    `drop` = x[["drop"]]
  )
}

