# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1PodFailurePolicy
#'
#' PodFailurePolicy describes how failed pods influence the backoffLimit.
#' @name V1PodFailurePolicy
#' @noMd
#' @export
V1PodFailurePolicy <- R6::R6Class(
  "V1PodFailurePolicy",
  public = list(
    `rules` = NULL
    ,
    #' @description Construct.
    initialize = function(`rules` = NULL) {
      self$`rules` <- `rules`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["rules"]] <- if (!is.null(self$`rules`)) lapply(self$`rules`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1PodFailurePolicy$from_list <- function(x) {
  V1PodFailurePolicy$new(
    `rules` = if (is.null(x[["rules"]])) NULL else lapply(x[["rules"]], V1PodFailurePolicyRule$from_list)
  )
}

V1PodFailurePolicy$required_fields <- c("rules")

