# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ContainerStateWaiting
#'
#' ContainerStateWaiting is a waiting state of a container.
#' @name V1ContainerStateWaiting
#' @noMd
#' @export
V1ContainerStateWaiting <- R6::R6Class(
  "V1ContainerStateWaiting",
  public = list(
    `message` = NULL,
    `reason` = NULL
    ,
    #' @description Construct.
    initialize = function(`message` = NULL, `reason` = NULL) {
      self$`message` <- `message`
      self$`reason` <- `reason`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["message"]] <- self$`message`
      out[["reason"]] <- self$`reason`
      drop_nulls_deep(out)
    }
  )
)

V1ContainerStateWaiting$from_list <- function(x) {
  V1ContainerStateWaiting$new(
    `message` = x[["message"]],
    `reason` = x[["reason"]]
  )
}

