# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1DaemonSetUpdateStrategy
#'
#' DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
#' @name V1DaemonSetUpdateStrategy
#' @noMd
#' @export
V1DaemonSetUpdateStrategy <- R6::R6Class(
  "V1DaemonSetUpdateStrategy",
  public = list(
    `rolling_update` = NULL,
    `type` = NULL
    ,
    #' @description Construct.
    initialize = function(`rolling_update` = NULL, `type` = NULL) {
      self$`rolling_update` <- `rolling_update`
      self$`type` <- `type`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["rollingUpdate"]] <- if (!is.null(self$`rolling_update`)) self$`rolling_update`$to_list() else NULL
      out[["type"]] <- self$`type`
      drop_nulls_deep(out)
    }
  )
)

V1DaemonSetUpdateStrategy$from_list <- function(x) {
  V1DaemonSetUpdateStrategy$new(
    `rolling_update` = if (is.null(x[["rollingUpdate"]])) NULL else V1RollingUpdateDaemonSet$from_list(x[["rollingUpdate"]]),
    `type` = x[["type"]]
  )
}

