# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1beta1ServiceCIDRStatus
#'
#' ServiceCIDRStatus describes the current state of the ServiceCIDR.
#' @name V1beta1ServiceCIDRStatus
#' @noMd
#' @export
V1beta1ServiceCIDRStatus <- R6::R6Class(
  "V1beta1ServiceCIDRStatus",
  public = list(
    `conditions` = NULL
    ,
    #' @description Construct.
    initialize = function(`conditions` = NULL) {
      self$`conditions` <- `conditions`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1beta1ServiceCIDRStatus$from_list <- function(x) {
  V1beta1ServiceCIDRStatus$new(
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1Condition$from_list)
  )
}

