# Generated by tools/gen/generate.R -- do not edit by hand.

#' ApiextensionsV1Api
#'
#' Typed Kubernetes API client for the `ApiextensionsV1` surface. See generated methods for available operations.
#' @name ApiextensionsV1Api
#' @noMd
#' @export
ApiextensionsV1Api <- R6::R6Class(
  "ApiextensionsV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getApiextensionsV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listApiextensionsV1CustomResourceDefinition
    #' list or watch objects of kind CustomResourceDefinition
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_custom_resource_definition = function(pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "GET",
        path_params = list(),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinitionList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createApiextensionsV1CustomResourceDefinition
    #' create a CustomResourceDefinition
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_custom_resource_definition = function(body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "POST",
        path_params = list(),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteApiextensionsV1CollectionCustomResourceDefinition
    #' delete collection of CustomResourceDefinition
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_custom_resource_definition = function(pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "DELETE",
        path_params = list(),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readApiextensionsV1CustomResourceDefinition
    #' read the specified CustomResourceDefinition
    #' @param name
    #' @param pretty = NULL
    read_custom_resource_definition = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceApiextensionsV1CustomResourceDefinition
    #' replace the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_custom_resource_definition = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchApiextensionsV1CustomResourceDefinition
    #' partially update the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_custom_resource_definition = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteApiextensionsV1CustomResourceDefinition
    #' delete a CustomResourceDefinition
    #' @param name
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_custom_resource_definition = function(name, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readApiextensionsV1CustomResourceDefinitionStatus
    #' read status of the specified CustomResourceDefinition
    #' @param name
    #' @param pretty = NULL
    read_custom_resource_definition_status = function(name, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceApiextensionsV1CustomResourceDefinitionStatus
    #' replace status of the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_custom_resource_definition_status = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchApiextensionsV1CustomResourceDefinitionStatus
    #' partially update status of the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_custom_resource_definition_status = function(name, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' watchApiextensionsV1CustomResourceDefinitionList
    #' watch individual changes to a list of CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_custom_resource_definition_list = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchApiextensionsV1CustomResourceDefinition
    #' watch changes to an object of kind CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_custom_resource_definition = function(name, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

