# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha1ClusterTrustBundle
#'
#' ClusterTrustBundle is a cluster-scoped container for X.509 trust anchors (root certificates).
#' 
#' ClusterTrustBundle objects are considered to be readable by any authenticated user in the cluster, because they can be mounted by pods using the `clusterTrustBundle` projection.  All service accounts have read access to ClusterTrustBundles by default.  Users who only have namespace-level access to a cluster can read ClusterTrustBundles by impersonating a serviceaccount that they have access to.
#' 
#' It can be optionally associated with a particular assigner, in which case it contains one valid set of trust anchors for that signer. Signers may have multiple associated ClusterTrustBundles; each is an independent set of trust anchors for that signer. Admission control is used to enforce that only users with permissions on the signer can create or modify the corresponding bundle.
#' @name V1alpha1ClusterTrustBundle
#' @noMd
#' @export
V1alpha1ClusterTrustBundle <- R6::R6Class(
  "V1alpha1ClusterTrustBundle",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `spec` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `spec` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`spec` <- `spec`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["spec"]] <- if (!is.null(self$`spec`)) self$`spec`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1alpha1ClusterTrustBundle$from_list <- function(x) {
  V1alpha1ClusterTrustBundle$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `spec` = if (is.null(x[["spec"]])) NULL else V1alpha1ClusterTrustBundleSpec$from_list(x[["spec"]])
  )
}

V1alpha1ClusterTrustBundle$required_fields <- c("spec")

