# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ScaleSpec
#'
#' ScaleSpec describes the attributes of a scale subresource.
#' @name V1ScaleSpec
#' @noMd
#' @export
V1ScaleSpec <- R6::R6Class(
  "V1ScaleSpec",
  public = list(
    `replicas` = NULL
    ,
    #' @description Construct.
    initialize = function(`replicas` = NULL) {
      self$`replicas` <- `replicas`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["replicas"]] <- self$`replicas`
      drop_nulls_deep(out)
    }
  )
)

V1ScaleSpec$from_list <- function(x) {
  V1ScaleSpec$new(
    `replicas` = x[["replicas"]]
  )
}

