# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1VolumeAttachment
#'
#' VolumeAttachment captures the intent to attach or detach the specified volume to/from the specified node.
#' 
#' VolumeAttachment objects are non-namespaced.
#' @name V1VolumeAttachment
#' @noMd
#' @export
V1VolumeAttachment <- R6::R6Class(
  "V1VolumeAttachment",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `spec` = NULL,
    `status` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `spec` = NULL, `status` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`spec` <- `spec`
      self$`status` <- `status`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["spec"]] <- if (!is.null(self$`spec`)) self$`spec`$to_list() else NULL
      out[["status"]] <- if (!is.null(self$`status`)) self$`status`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1VolumeAttachment$from_list <- function(x) {
  V1VolumeAttachment$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `spec` = if (is.null(x[["spec"]])) NULL else V1VolumeAttachmentSpec$from_list(x[["spec"]]),
    `status` = if (is.null(x[["status"]])) NULL else V1VolumeAttachmentStatus$from_list(x[["status"]])
  )
}

V1VolumeAttachment$required_fields <- c("spec")

