# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1PersistentVolumeClaimStatus
#'
#' PersistentVolumeClaimStatus is the current status of a persistent volume claim.
#' @name V1PersistentVolumeClaimStatus
#' @noMd
#' @export
V1PersistentVolumeClaimStatus <- R6::R6Class(
  "V1PersistentVolumeClaimStatus",
  public = list(
    `access_modes` = NULL,
    `allocated_resource_statuses` = NULL,
    `allocated_resources` = NULL,
    `capacity` = NULL,
    `conditions` = NULL,
    `current_volume_attributes_class_name` = NULL,
    `modify_volume_status` = NULL,
    `phase` = NULL
    ,
    #' @description Construct.
    initialize = function(`access_modes` = NULL, `allocated_resource_statuses` = NULL, `allocated_resources` = NULL, `capacity` = NULL, `conditions` = NULL, `current_volume_attributes_class_name` = NULL, `modify_volume_status` = NULL, `phase` = NULL) {
      self$`access_modes` <- `access_modes`
      self$`allocated_resource_statuses` <- `allocated_resource_statuses`
      self$`allocated_resources` <- `allocated_resources`
      self$`capacity` <- `capacity`
      self$`conditions` <- `conditions`
      self$`current_volume_attributes_class_name` <- `current_volume_attributes_class_name`
      self$`modify_volume_status` <- `modify_volume_status`
      self$`phase` <- `phase`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["accessModes"]] <- self$`access_modes`
      out[["allocatedResourceStatuses"]] <- self$`allocated_resource_statuses`
      out[["allocatedResources"]] <- if (!is.null(self$`allocated_resources`)) lapply(self$`allocated_resources`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["capacity"]] <- if (!is.null(self$`capacity`)) lapply(self$`capacity`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["conditions"]] <- if (!is.null(self$`conditions`)) lapply(self$`conditions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["currentVolumeAttributesClassName"]] <- self$`current_volume_attributes_class_name`
      out[["modifyVolumeStatus"]] <- if (!is.null(self$`modify_volume_status`)) self$`modify_volume_status`$to_list() else NULL
      out[["phase"]] <- self$`phase`
      drop_nulls_deep(out)
    }
  )
)

V1PersistentVolumeClaimStatus$from_list <- function(x) {
  V1PersistentVolumeClaimStatus$new(
    `access_modes` = x[["accessModes"]],
    `allocated_resource_statuses` = x[["allocatedResourceStatuses"]],
    `allocated_resources` = if (is.null(x[["allocatedResources"]])) NULL else lapply(x[["allocatedResources"]], Quantity$from_list),
    `capacity` = if (is.null(x[["capacity"]])) NULL else lapply(x[["capacity"]], Quantity$from_list),
    `conditions` = if (is.null(x[["conditions"]])) NULL else lapply(x[["conditions"]], V1PersistentVolumeClaimCondition$from_list),
    `current_volume_attributes_class_name` = x[["currentVolumeAttributesClassName"]],
    `modify_volume_status` = if (is.null(x[["modifyVolumeStatus"]])) NULL else V1ModifyVolumeStatus$from_list(x[["modifyVolumeStatus"]]),
    `phase` = x[["phase"]]
  )
}

