# Generated by tools/gen/generate.R -- do not edit by hand.

#' CoreV1EndpointPort
#'
#' EndpointPort is a tuple that describes a single port.
#' @name CoreV1EndpointPort
#' @noMd
#' @export
CoreV1EndpointPort <- R6::R6Class(
  "CoreV1EndpointPort",
  public = list(
    `app_protocol` = NULL,
    `name` = NULL,
    `port` = NULL,
    `protocol` = NULL
    ,
    #' @description Construct.
    initialize = function(`app_protocol` = NULL, `name` = NULL, `port` = NULL, `protocol` = NULL) {
      self$`app_protocol` <- `app_protocol`
      self$`name` <- `name`
      self$`port` <- `port`
      self$`protocol` <- `protocol`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["appProtocol"]] <- self$`app_protocol`
      out[["name"]] <- self$`name`
      out[["port"]] <- self$`port`
      out[["protocol"]] <- self$`protocol`
      drop_nulls_deep(out)
    }
  )
)

CoreV1EndpointPort$from_list <- function(x) {
  CoreV1EndpointPort$new(
    `app_protocol` = x[["appProtocol"]],
    `name` = x[["name"]],
    `port` = x[["port"]],
    `protocol` = x[["protocol"]]
  )
}

CoreV1EndpointPort$required_fields <- c("port")

