# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CSIVolumeSource
#'
#' Represents a source location of a volume to mount, managed by an external CSI driver
#' @name V1CSIVolumeSource
#' @noMd
#' @export
V1CSIVolumeSource <- R6::R6Class(
  "V1CSIVolumeSource",
  public = list(
    `driver` = NULL,
    `fs_type` = NULL,
    `node_publish_secret_ref` = NULL,
    `read_only` = NULL,
    `volume_attributes` = NULL
    ,
    #' @description Construct.
    initialize = function(`driver` = NULL, `fs_type` = NULL, `node_publish_secret_ref` = NULL, `read_only` = NULL, `volume_attributes` = NULL) {
      self$`driver` <- `driver`
      self$`fs_type` <- `fs_type`
      self$`node_publish_secret_ref` <- `node_publish_secret_ref`
      self$`read_only` <- `read_only`
      self$`volume_attributes` <- `volume_attributes`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["driver"]] <- self$`driver`
      out[["fsType"]] <- self$`fs_type`
      out[["nodePublishSecretRef"]] <- if (!is.null(self$`node_publish_secret_ref`)) self$`node_publish_secret_ref`$to_list() else NULL
      out[["readOnly"]] <- self$`read_only`
      out[["volumeAttributes"]] <- self$`volume_attributes`
      drop_nulls_deep(out)
    }
  )
)

V1CSIVolumeSource$from_list <- function(x) {
  V1CSIVolumeSource$new(
    `driver` = x[["driver"]],
    `fs_type` = x[["fsType"]],
    `node_publish_secret_ref` = if (is.null(x[["nodePublishSecretRef"]])) NULL else V1LocalObjectReference$from_list(x[["nodePublishSecretRef"]]),
    `read_only` = x[["readOnly"]],
    `volume_attributes` = x[["volumeAttributes"]]
  )
}

V1CSIVolumeSource$required_fields <- c("driver")

