# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1FCVolumeSource
#'
#' Represents a Fibre Channel volume. Fibre Channel volumes can only be mounted as read/write once. Fibre Channel volumes support ownership management and SELinux relabeling.
#' @name V1FCVolumeSource
#' @noMd
#' @export
V1FCVolumeSource <- R6::R6Class(
  "V1FCVolumeSource",
  public = list(
    `fs_type` = NULL,
    `lun` = NULL,
    `read_only` = NULL,
    `target_ww_ns` = NULL,
    `wwids` = NULL
    ,
    #' @description Construct.
    initialize = function(`fs_type` = NULL, `lun` = NULL, `read_only` = NULL, `target_ww_ns` = NULL, `wwids` = NULL) {
      self$`fs_type` <- `fs_type`
      self$`lun` <- `lun`
      self$`read_only` <- `read_only`
      self$`target_ww_ns` <- `target_ww_ns`
      self$`wwids` <- `wwids`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["fsType"]] <- self$`fs_type`
      out[["lun"]] <- self$`lun`
      out[["readOnly"]] <- self$`read_only`
      out[["targetWWNs"]] <- self$`target_ww_ns`
      out[["wwids"]] <- self$`wwids`
      drop_nulls_deep(out)
    }
  )
)

V1FCVolumeSource$from_list <- function(x) {
  V1FCVolumeSource$new(
    `fs_type` = x[["fsType"]],
    `lun` = x[["lun"]],
    `read_only` = x[["readOnly"]],
    `target_ww_ns` = x[["targetWWNs"]],
    `wwids` = x[["wwids"]]
  )
}

