# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ResourceRule
#'
#' ResourceRule is the list of actions the subject is allowed to perform on resources. The list ordering isn't significant, may contain duplicates, and possibly be incomplete.
#' @name V1ResourceRule
#' @noMd
#' @export
V1ResourceRule <- R6::R6Class(
  "V1ResourceRule",
  public = list(
    `api_groups` = NULL,
    `resource_names` = NULL,
    `resources` = NULL,
    `verbs` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_groups` = NULL, `resource_names` = NULL, `resources` = NULL, `verbs` = NULL) {
      self$`api_groups` <- `api_groups`
      self$`resource_names` <- `resource_names`
      self$`resources` <- `resources`
      self$`verbs` <- `verbs`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiGroups"]] <- self$`api_groups`
      out[["resourceNames"]] <- self$`resource_names`
      out[["resources"]] <- self$`resources`
      out[["verbs"]] <- self$`verbs`
      drop_nulls_deep(out)
    }
  )
)

V1ResourceRule$from_list <- function(x) {
  V1ResourceRule$new(
    `api_groups` = x[["apiGroups"]],
    `resource_names` = x[["resourceNames"]],
    `resources` = x[["resources"]],
    `verbs` = x[["verbs"]]
  )
}

V1ResourceRule$required_fields <- c("verbs")

