# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CustomResourceSubresourceStatus
#'
#' CustomResourceSubresourceStatus defines how to serve the status subresource for CustomResources. Status is represented by the `.status` JSON path inside of a CustomResource. When set, * exposes a /status subresource for the custom resource * PUT requests to the /status subresource take a custom resource object, and ignore changes to anything except the status stanza * PUT/POST/PATCH requests to the custom resource ignore changes to the status stanza
#' @name V1CustomResourceSubresourceStatus
#' @noMd
#' @export
V1CustomResourceSubresourceStatus <- R6::R6Class(
  "V1CustomResourceSubresourceStatus",
  public = list(
    #' @field value Underlying scalar / unstructured value.
    value = NULL,
    #' @description Construct.
    #' @param value The underlying value.
    initialize = function(value = NULL) { self$value <- value },
    #' @description Return the underlying value (no key wrapping).
    to_list = function() self$value
  )
)

V1CustomResourceSubresourceStatus$from_list <- function(x) V1CustomResourceSubresourceStatus$new(value = x)

