# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1SelfSubjectAccessReviewSpec
#'
#' SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
#' @name V1SelfSubjectAccessReviewSpec
#' @noMd
#' @export
V1SelfSubjectAccessReviewSpec <- R6::R6Class(
  "V1SelfSubjectAccessReviewSpec",
  public = list(
    `non_resource_attributes` = NULL,
    `resource_attributes` = NULL
    ,
    #' @description Construct.
    initialize = function(`non_resource_attributes` = NULL, `resource_attributes` = NULL) {
      self$`non_resource_attributes` <- `non_resource_attributes`
      self$`resource_attributes` <- `resource_attributes`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["nonResourceAttributes"]] <- if (!is.null(self$`non_resource_attributes`)) self$`non_resource_attributes`$to_list() else NULL
      out[["resourceAttributes"]] <- if (!is.null(self$`resource_attributes`)) self$`resource_attributes`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1SelfSubjectAccessReviewSpec$from_list <- function(x) {
  V1SelfSubjectAccessReviewSpec$new(
    `non_resource_attributes` = if (is.null(x[["nonResourceAttributes"]])) NULL else V1NonResourceAttributes$from_list(x[["nonResourceAttributes"]]),
    `resource_attributes` = if (is.null(x[["resourceAttributes"]])) NULL else V1ResourceAttributes$from_list(x[["resourceAttributes"]])
  )
}

