# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1AWSElasticBlockStoreVolumeSource
#'
#' Represents a Persistent Disk resource in AWS.
#' 
#' An AWS EBS disk must exist before mounting to a container. The disk must also be in the same AWS zone as the kubelet. An AWS EBS disk can only be mounted as read/write once. AWS EBS volumes support ownership management and SELinux relabeling.
#' @name V1AWSElasticBlockStoreVolumeSource
#' @noMd
#' @export
V1AWSElasticBlockStoreVolumeSource <- R6::R6Class(
  "V1AWSElasticBlockStoreVolumeSource",
  public = list(
    `fs_type` = NULL,
    `partition` = NULL,
    `read_only` = NULL,
    `volume_id` = NULL
    ,
    #' @description Construct.
    initialize = function(`fs_type` = NULL, `partition` = NULL, `read_only` = NULL, `volume_id` = NULL) {
      self$`fs_type` <- `fs_type`
      self$`partition` <- `partition`
      self$`read_only` <- `read_only`
      self$`volume_id` <- `volume_id`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["fsType"]] <- self$`fs_type`
      out[["partition"]] <- self$`partition`
      out[["readOnly"]] <- self$`read_only`
      out[["volumeID"]] <- self$`volume_id`
      drop_nulls_deep(out)
    }
  )
)

V1AWSElasticBlockStoreVolumeSource$from_list <- function(x) {
  V1AWSElasticBlockStoreVolumeSource$new(
    `fs_type` = x[["fsType"]],
    `partition` = x[["partition"]],
    `read_only` = x[["readOnly"]],
    `volume_id` = x[["volumeID"]]
  )
}

V1AWSElasticBlockStoreVolumeSource$required_fields <- c("volumeID")

