# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1StatefulSet
#'
#' StatefulSet represents a set of pods with consistent identities. Identities are defined as:
#'   - Network: A single stable DNS and hostname.
#'   - Storage: As many VolumeClaims as requested.
#' 
#' The StatefulSet guarantees that a given network identity will always map to the same storage identity.
#' @name V1StatefulSet
#' @noMd
#' @export
V1StatefulSet <- R6::R6Class(
  "V1StatefulSet",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `spec` = NULL,
    `status` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `spec` = NULL, `status` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`spec` <- `spec`
      self$`status` <- `status`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["spec"]] <- if (!is.null(self$`spec`)) self$`spec`$to_list() else NULL
      out[["status"]] <- if (!is.null(self$`status`)) self$`status`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1StatefulSet$from_list <- function(x) {
  V1StatefulSet$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `spec` = if (is.null(x[["spec"]])) NULL else V1StatefulSetSpec$from_list(x[["spec"]]),
    `status` = if (is.null(x[["status"]])) NULL else V1StatefulSetStatus$from_list(x[["status"]])
  )
}

