# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1DownwardAPIVolumeFile
#'
#' DownwardAPIVolumeFile represents information to create the file containing the pod field
#' @name V1DownwardAPIVolumeFile
#' @noMd
#' @export
V1DownwardAPIVolumeFile <- R6::R6Class(
  "V1DownwardAPIVolumeFile",
  public = list(
    `field_ref` = NULL,
    `mode` = NULL,
    `path` = NULL,
    `resource_field_ref` = NULL
    ,
    #' @description Construct.
    initialize = function(`field_ref` = NULL, `mode` = NULL, `path` = NULL, `resource_field_ref` = NULL) {
      self$`field_ref` <- `field_ref`
      self$`mode` <- `mode`
      self$`path` <- `path`
      self$`resource_field_ref` <- `resource_field_ref`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["fieldRef"]] <- if (!is.null(self$`field_ref`)) self$`field_ref`$to_list() else NULL
      out[["mode"]] <- self$`mode`
      out[["path"]] <- self$`path`
      out[["resourceFieldRef"]] <- if (!is.null(self$`resource_field_ref`)) self$`resource_field_ref`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1DownwardAPIVolumeFile$from_list <- function(x) {
  V1DownwardAPIVolumeFile$new(
    `field_ref` = if (is.null(x[["fieldRef"]])) NULL else V1ObjectFieldSelector$from_list(x[["fieldRef"]]),
    `mode` = x[["mode"]],
    `path` = x[["path"]],
    `resource_field_ref` = if (is.null(x[["resourceFieldRef"]])) NULL else V1ResourceFieldSelector$from_list(x[["resourceFieldRef"]])
  )
}

V1DownwardAPIVolumeFile$required_fields <- c("path")

