# Generated by tools/gen/generate.R -- do not edit by hand.

#' V2HorizontalPodAutoscalerBehavior
#'
#' HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).
#' @name V2HorizontalPodAutoscalerBehavior
#' @noMd
#' @export
V2HorizontalPodAutoscalerBehavior <- R6::R6Class(
  "V2HorizontalPodAutoscalerBehavior",
  public = list(
    `scale_down` = NULL,
    `scale_up` = NULL
    ,
    #' @description Construct.
    initialize = function(`scale_down` = NULL, `scale_up` = NULL) {
      self$`scale_down` <- `scale_down`
      self$`scale_up` <- `scale_up`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["scaleDown"]] <- if (!is.null(self$`scale_down`)) self$`scale_down`$to_list() else NULL
      out[["scaleUp"]] <- if (!is.null(self$`scale_up`)) self$`scale_up`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V2HorizontalPodAutoscalerBehavior$from_list <- function(x) {
  V2HorizontalPodAutoscalerBehavior$new(
    `scale_down` = if (is.null(x[["scaleDown"]])) NULL else V2HPAScalingRules$from_list(x[["scaleDown"]]),
    `scale_up` = if (is.null(x[["scaleUp"]])) NULL else V2HPAScalingRules$from_list(x[["scaleUp"]])
  )
}

