# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3ResourceSlice
#'
#' ResourceSlice represents one or more resources in a pool of similar resources, managed by a common driver. A pool may span more than one ResourceSlice, and exactly how many ResourceSlices comprise a pool is determined by the driver.
#' 
#' At the moment, the only supported resources are devices with attributes and capacities. Each device in a given pool, regardless of how many ResourceSlices, must have a unique name. The ResourceSlice in which a device gets published may change over time. The unique identifier for a device is the tuple <driver name>, <pool name>, <device name>.
#' 
#' Whenever a driver needs to update a pool, it increments the pool.Spec.Pool.Generation number and updates all ResourceSlices with that new number and new resource definitions. A consumer must only use ResourceSlices with the highest generation number and ignore all others.
#' 
#' When allocating all resources in a pool matching certain criteria or when looking for the best solution among several different alternatives, a consumer should check the number of ResourceSlices in a pool (included in each ResourceSlice) to determine whether its view of a pool is complete and if not, should wait until the driver has completed updating the pool.
#' 
#' For resources that are not local to a node, the node name is not set. Instead, the driver may use a node selector to specify where the devices are available.
#' 
#' This is an alpha type and requires enabling the DynamicResourceAllocation feature gate.
#' @name V1alpha3ResourceSlice
#' @noMd
#' @export
V1alpha3ResourceSlice <- R6::R6Class(
  "V1alpha3ResourceSlice",
  public = list(
    `api_version` = NULL,
    `kind` = NULL,
    `metadata` = NULL,
    `spec` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `kind` = NULL, `metadata` = NULL, `spec` = NULL) {
      self$`api_version` <- `api_version`
      self$`kind` <- `kind`
      self$`metadata` <- `metadata`
      self$`spec` <- `spec`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["kind"]] <- self$`kind`
      out[["metadata"]] <- if (!is.null(self$`metadata`)) self$`metadata`$to_list() else NULL
      out[["spec"]] <- if (!is.null(self$`spec`)) self$`spec`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V1alpha3ResourceSlice$from_list <- function(x) {
  V1alpha3ResourceSlice$new(
    `api_version` = x[["apiVersion"]],
    `kind` = x[["kind"]],
    `metadata` = if (is.null(x[["metadata"]])) NULL else V1ObjectMeta$from_list(x[["metadata"]]),
    `spec` = if (is.null(x[["spec"]])) NULL else V1alpha3ResourceSliceSpec$from_list(x[["spec"]])
  )
}

V1alpha3ResourceSlice$required_fields <- c("spec")

