# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ObjectReference
#'
#' ObjectReference contains enough information to let you inspect or modify the referred object.
#' @name V1ObjectReference
#' @noMd
#' @export
V1ObjectReference <- R6::R6Class(
  "V1ObjectReference",
  public = list(
    `api_version` = NULL,
    `field_path` = NULL,
    `kind` = NULL,
    `name` = NULL,
    `namespace` = NULL,
    `resource_version` = NULL,
    `uid` = NULL
    ,
    #' @description Construct.
    initialize = function(`api_version` = NULL, `field_path` = NULL, `kind` = NULL, `name` = NULL, `namespace` = NULL, `resource_version` = NULL, `uid` = NULL) {
      self$`api_version` <- `api_version`
      self$`field_path` <- `field_path`
      self$`kind` <- `kind`
      self$`name` <- `name`
      self$`namespace` <- `namespace`
      self$`resource_version` <- `resource_version`
      self$`uid` <- `uid`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["apiVersion"]] <- self$`api_version`
      out[["fieldPath"]] <- self$`field_path`
      out[["kind"]] <- self$`kind`
      out[["name"]] <- self$`name`
      out[["namespace"]] <- self$`namespace`
      out[["resourceVersion"]] <- self$`resource_version`
      out[["uid"]] <- self$`uid`
      drop_nulls_deep(out)
    }
  )
)

V1ObjectReference$from_list <- function(x) {
  V1ObjectReference$new(
    `api_version` = x[["apiVersion"]],
    `field_path` = x[["fieldPath"]],
    `kind` = x[["kind"]],
    `name` = x[["name"]],
    `namespace` = x[["namespace"]],
    `resource_version` = x[["resourceVersion"]],
    `uid` = x[["uid"]]
  )
}

