# Generated by tools/gen/generate.R -- do not edit by hand.

#' CoordinationV1Api
#'
#' Typed Kubernetes API client for the `CoordinationV1` surface. See generated methods for available operations.
#' @name CoordinationV1Api
#' @noMd
#' @export
CoordinationV1Api <- R6::R6Class(
  "CoordinationV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getCoordinationV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listCoordinationV1LeaseForAllNamespaces
    #' list or watch objects of kind Lease
    list_lease_for_all_namespaces = function() {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/leases",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1LeaseList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listCoordinationV1NamespacedLease
    #' list or watch objects of kind Lease
    list_namespaced_lease = function() {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1LeaseList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createCoordinationV1NamespacedLease
    #' create a Lease
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_namespaced_lease = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Lease",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteCoordinationV1CollectionNamespacedLease
    #' delete collection of Lease
    #' @param dry_run = NULL
    delete_collection_namespaced_lease = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readCoordinationV1NamespacedLease
    #' read the specified Lease
    #' @param name
    read_namespaced_lease = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1Lease",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceCoordinationV1NamespacedLease
    #' replace the specified Lease
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_namespaced_lease = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Lease",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchCoordinationV1NamespacedLease
    #' partially update the specified Lease
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_namespaced_lease = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1Lease",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteCoordinationV1NamespacedLease
    #' delete a Lease
    #' @param name
    #' @param dry_run = NULL
    delete_namespaced_lease = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCoordinationV1LeaseListForAllNamespaces
    #' watch individual changes to a list of Lease. deprecated: use the 'watch' parameter with a list operation instead.
    watch_lease_list_for_all_namespaces = function() {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/watch/leases",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCoordinationV1NamespacedLeaseList
    #' watch individual changes to a list of Lease. deprecated: use the 'watch' parameter with a list operation instead.
    watch_namespaced_lease_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/watch/namespaces/{namespace}/leases",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCoordinationV1NamespacedLease
    #' watch changes to an object of kind Lease. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_namespaced_lease = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/coordination.k8s.io/v1/watch/namespaces/{namespace}/leases/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

