# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CustomResourceDefinitionSpec
#'
#' CustomResourceDefinitionSpec describes how a user wants their resource to appear
#' @name V1CustomResourceDefinitionSpec
#' @noMd
#' @export
V1CustomResourceDefinitionSpec <- R6::R6Class(
  "V1CustomResourceDefinitionSpec",
  public = list(
    `conversion` = NULL,
    `group` = NULL,
    `names` = NULL,
    `preserve_unknown_fields` = NULL,
    `scope` = NULL,
    `versions` = NULL
    ,
    #' @description Construct.
    initialize = function(`conversion` = NULL, `group` = NULL, `names` = NULL, `preserve_unknown_fields` = NULL, `scope` = NULL, `versions` = NULL) {
      self$`conversion` <- `conversion`
      self$`group` <- `group`
      self$`names` <- `names`
      self$`preserve_unknown_fields` <- `preserve_unknown_fields`
      self$`scope` <- `scope`
      self$`versions` <- `versions`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["conversion"]] <- if (!is.null(self$`conversion`)) self$`conversion`$to_list() else NULL
      out[["group"]] <- self$`group`
      out[["names"]] <- if (!is.null(self$`names`)) self$`names`$to_list() else NULL
      out[["preserveUnknownFields"]] <- self$`preserve_unknown_fields`
      out[["scope"]] <- self$`scope`
      out[["versions"]] <- if (!is.null(self$`versions`)) lapply(self$`versions`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1CustomResourceDefinitionSpec$from_list <- function(x) {
  V1CustomResourceDefinitionSpec$new(
    `conversion` = if (is.null(x[["conversion"]])) NULL else V1CustomResourceConversion$from_list(x[["conversion"]]),
    `group` = x[["group"]],
    `names` = if (is.null(x[["names"]])) NULL else V1CustomResourceDefinitionNames$from_list(x[["names"]]),
    `preserve_unknown_fields` = x[["preserveUnknownFields"]],
    `scope` = x[["scope"]],
    `versions` = if (is.null(x[["versions"]])) NULL else lapply(x[["versions"]], V1CustomResourceDefinitionVersion$from_list)
  )
}

V1CustomResourceDefinitionSpec$required_fields <- c("group", "names", "scope", "versions")

