# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1Container
#'
#' A single application container that you want to run within a pod.
#' @name V1Container
#' @noMd
#' @export
V1Container <- R6::R6Class(
  "V1Container",
  public = list(
    `args` = NULL,
    `command` = NULL,
    `env` = NULL,
    `env_from` = NULL,
    `image` = NULL,
    `image_pull_policy` = NULL,
    `lifecycle` = NULL,
    `liveness_probe` = NULL,
    `name` = NULL,
    `ports` = NULL,
    `readiness_probe` = NULL,
    `resize_policy` = NULL,
    `resources` = NULL,
    `restart_policy` = NULL,
    `security_context` = NULL,
    `startup_probe` = NULL,
    `stdin` = NULL,
    `stdin_once` = NULL,
    `termination_message_path` = NULL,
    `termination_message_policy` = NULL,
    `tty` = NULL,
    `volume_devices` = NULL,
    `volume_mounts` = NULL,
    `working_dir` = NULL
    ,
    #' @description Construct.
    initialize = function(`args` = NULL, `command` = NULL, `env` = NULL, `env_from` = NULL, `image` = NULL, `image_pull_policy` = NULL, `lifecycle` = NULL, `liveness_probe` = NULL, `name` = NULL, `ports` = NULL, `readiness_probe` = NULL, `resize_policy` = NULL, `resources` = NULL, `restart_policy` = NULL, `security_context` = NULL, `startup_probe` = NULL, `stdin` = NULL, `stdin_once` = NULL, `termination_message_path` = NULL, `termination_message_policy` = NULL, `tty` = NULL, `volume_devices` = NULL, `volume_mounts` = NULL, `working_dir` = NULL) {
      self$`args` <- `args`
      self$`command` <- `command`
      self$`env` <- `env`
      self$`env_from` <- `env_from`
      self$`image` <- `image`
      self$`image_pull_policy` <- `image_pull_policy`
      self$`lifecycle` <- `lifecycle`
      self$`liveness_probe` <- `liveness_probe`
      self$`name` <- `name`
      self$`ports` <- `ports`
      self$`readiness_probe` <- `readiness_probe`
      self$`resize_policy` <- `resize_policy`
      self$`resources` <- `resources`
      self$`restart_policy` <- `restart_policy`
      self$`security_context` <- `security_context`
      self$`startup_probe` <- `startup_probe`
      self$`stdin` <- `stdin`
      self$`stdin_once` <- `stdin_once`
      self$`termination_message_path` <- `termination_message_path`
      self$`termination_message_policy` <- `termination_message_policy`
      self$`tty` <- `tty`
      self$`volume_devices` <- `volume_devices`
      self$`volume_mounts` <- `volume_mounts`
      self$`working_dir` <- `working_dir`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["args"]] <- self$`args`
      out[["command"]] <- self$`command`
      out[["env"]] <- if (!is.null(self$`env`)) lapply(self$`env`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["envFrom"]] <- if (!is.null(self$`env_from`)) lapply(self$`env_from`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["image"]] <- self$`image`
      out[["imagePullPolicy"]] <- self$`image_pull_policy`
      out[["lifecycle"]] <- if (!is.null(self$`lifecycle`)) self$`lifecycle`$to_list() else NULL
      out[["livenessProbe"]] <- if (!is.null(self$`liveness_probe`)) self$`liveness_probe`$to_list() else NULL
      out[["name"]] <- self$`name`
      out[["ports"]] <- if (!is.null(self$`ports`)) lapply(self$`ports`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["readinessProbe"]] <- if (!is.null(self$`readiness_probe`)) self$`readiness_probe`$to_list() else NULL
      out[["resizePolicy"]] <- if (!is.null(self$`resize_policy`)) lapply(self$`resize_policy`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["resources"]] <- if (!is.null(self$`resources`)) self$`resources`$to_list() else NULL
      out[["restartPolicy"]] <- self$`restart_policy`
      out[["securityContext"]] <- if (!is.null(self$`security_context`)) self$`security_context`$to_list() else NULL
      out[["startupProbe"]] <- if (!is.null(self$`startup_probe`)) self$`startup_probe`$to_list() else NULL
      out[["stdin"]] <- self$`stdin`
      out[["stdinOnce"]] <- self$`stdin_once`
      out[["terminationMessagePath"]] <- self$`termination_message_path`
      out[["terminationMessagePolicy"]] <- self$`termination_message_policy`
      out[["tty"]] <- self$`tty`
      out[["volumeDevices"]] <- if (!is.null(self$`volume_devices`)) lapply(self$`volume_devices`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["volumeMounts"]] <- if (!is.null(self$`volume_mounts`)) lapply(self$`volume_mounts`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["workingDir"]] <- self$`working_dir`
      drop_nulls_deep(out)
    }
  )
)

V1Container$from_list <- function(x) {
  V1Container$new(
    `args` = x[["args"]],
    `command` = x[["command"]],
    `env` = if (is.null(x[["env"]])) NULL else lapply(x[["env"]], V1EnvVar$from_list),
    `env_from` = if (is.null(x[["envFrom"]])) NULL else lapply(x[["envFrom"]], V1EnvFromSource$from_list),
    `image` = x[["image"]],
    `image_pull_policy` = x[["imagePullPolicy"]],
    `lifecycle` = if (is.null(x[["lifecycle"]])) NULL else V1Lifecycle$from_list(x[["lifecycle"]]),
    `liveness_probe` = if (is.null(x[["livenessProbe"]])) NULL else V1Probe$from_list(x[["livenessProbe"]]),
    `name` = x[["name"]],
    `ports` = if (is.null(x[["ports"]])) NULL else lapply(x[["ports"]], V1ContainerPort$from_list),
    `readiness_probe` = if (is.null(x[["readinessProbe"]])) NULL else V1Probe$from_list(x[["readinessProbe"]]),
    `resize_policy` = if (is.null(x[["resizePolicy"]])) NULL else lapply(x[["resizePolicy"]], V1ContainerResizePolicy$from_list),
    `resources` = if (is.null(x[["resources"]])) NULL else V1ResourceRequirements$from_list(x[["resources"]]),
    `restart_policy` = x[["restartPolicy"]],
    `security_context` = if (is.null(x[["securityContext"]])) NULL else V1SecurityContext$from_list(x[["securityContext"]]),
    `startup_probe` = if (is.null(x[["startupProbe"]])) NULL else V1Probe$from_list(x[["startupProbe"]]),
    `stdin` = x[["stdin"]],
    `stdin_once` = x[["stdinOnce"]],
    `termination_message_path` = x[["terminationMessagePath"]],
    `termination_message_policy` = x[["terminationMessagePolicy"]],
    `tty` = x[["tty"]],
    `volume_devices` = if (is.null(x[["volumeDevices"]])) NULL else lapply(x[["volumeDevices"]], V1VolumeDevice$from_list),
    `volume_mounts` = if (is.null(x[["volumeMounts"]])) NULL else lapply(x[["volumeMounts"]], V1VolumeMount$from_list),
    `working_dir` = x[["workingDir"]]
  )
}

V1Container$required_fields <- c("name")

