# Generated by tools/gen/generate.R -- do not edit by hand.

#' AuthorizationV1Api
#'
#' Typed Kubernetes API client for the `AuthorizationV1` surface. See generated methods for available operations.
#' @name AuthorizationV1Api
#' @noMd
#' @export
AuthorizationV1Api <- R6::R6Class(
  "AuthorizationV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getAuthorizationV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/authorization.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' createAuthorizationV1NamespacedLocalSubjectAccessReview
    #' create a LocalSubjectAccessReview
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_namespaced_local_subject_access_review = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/authorization.k8s.io/v1/namespaces/{namespace}/localsubjectaccessreviews",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1LocalSubjectAccessReview",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAuthorizationV1SelfSubjectAccessReview
    #' create a SelfSubjectAccessReview
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_self_subject_access_review = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/authorization.k8s.io/v1/selfsubjectaccessreviews",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1SelfSubjectAccessReview",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAuthorizationV1SelfSubjectRulesReview
    #' create a SelfSubjectRulesReview
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_self_subject_rules_review = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/authorization.k8s.io/v1/selfsubjectrulesreviews",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1SelfSubjectRulesReview",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAuthorizationV1SubjectAccessReview
    #' create a SubjectAccessReview
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_subject_access_review = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/authorization.k8s.io/v1/subjectaccessreviews",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1SubjectAccessReview",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

