# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1NetworkPolicySpec
#'
#' NetworkPolicySpec provides the specification of a NetworkPolicy
#' @name V1NetworkPolicySpec
#' @noMd
#' @export
V1NetworkPolicySpec <- R6::R6Class(
  "V1NetworkPolicySpec",
  public = list(
    `egress` = NULL,
    `ingress` = NULL,
    `pod_selector` = NULL,
    `policy_types` = NULL
    ,
    #' @description Construct.
    initialize = function(`egress` = NULL, `ingress` = NULL, `pod_selector` = NULL, `policy_types` = NULL) {
      self$`egress` <- `egress`
      self$`ingress` <- `ingress`
      self$`pod_selector` <- `pod_selector`
      self$`policy_types` <- `policy_types`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["egress"]] <- if (!is.null(self$`egress`)) lapply(self$`egress`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["ingress"]] <- if (!is.null(self$`ingress`)) lapply(self$`ingress`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["podSelector"]] <- if (!is.null(self$`pod_selector`)) self$`pod_selector`$to_list() else NULL
      out[["policyTypes"]] <- self$`policy_types`
      drop_nulls_deep(out)
    }
  )
)

V1NetworkPolicySpec$from_list <- function(x) {
  V1NetworkPolicySpec$new(
    `egress` = if (is.null(x[["egress"]])) NULL else lapply(x[["egress"]], V1NetworkPolicyEgressRule$from_list),
    `ingress` = if (is.null(x[["ingress"]])) NULL else lapply(x[["ingress"]], V1NetworkPolicyIngressRule$from_list),
    `pod_selector` = if (is.null(x[["podSelector"]])) NULL else V1LabelSelector$from_list(x[["podSelector"]]),
    `policy_types` = x[["policyTypes"]]
  )
}

V1NetworkPolicySpec$required_fields <- c("podSelector")

