# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1alpha3PodSchedulingContextSpec
#'
#' PodSchedulingContextSpec describes where resources for the Pod are needed.
#' @name V1alpha3PodSchedulingContextSpec
#' @noMd
#' @export
V1alpha3PodSchedulingContextSpec <- R6::R6Class(
  "V1alpha3PodSchedulingContextSpec",
  public = list(
    `potential_nodes` = NULL,
    `selected_node` = NULL
    ,
    #' @description Construct.
    initialize = function(`potential_nodes` = NULL, `selected_node` = NULL) {
      self$`potential_nodes` <- `potential_nodes`
      self$`selected_node` <- `selected_node`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["potentialNodes"]] <- self$`potential_nodes`
      out[["selectedNode"]] <- self$`selected_node`
      drop_nulls_deep(out)
    }
  )
)

V1alpha3PodSchedulingContextSpec$from_list <- function(x) {
  V1alpha3PodSchedulingContextSpec$new(
    `potential_nodes` = x[["potentialNodes"]],
    `selected_node` = x[["selectedNode"]]
  )
}

