# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1DownwardAPIVolumeSource
#'
#' DownwardAPIVolumeSource represents a volume containing downward API info. Downward API volumes support ownership management and SELinux relabeling.
#' @name V1DownwardAPIVolumeSource
#' @noMd
#' @export
V1DownwardAPIVolumeSource <- R6::R6Class(
  "V1DownwardAPIVolumeSource",
  public = list(
    `default_mode` = NULL,
    `items` = NULL
    ,
    #' @description Construct.
    initialize = function(`default_mode` = NULL, `items` = NULL) {
      self$`default_mode` <- `default_mode`
      self$`items` <- `items`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["defaultMode"]] <- self$`default_mode`
      out[["items"]] <- if (!is.null(self$`items`)) lapply(self$`items`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1DownwardAPIVolumeSource$from_list <- function(x) {
  V1DownwardAPIVolumeSource$new(
    `default_mode` = x[["defaultMode"]],
    `items` = if (is.null(x[["items"]])) NULL else lapply(x[["items"]], V1DownwardAPIVolumeFile$from_list)
  )
}

