# Generated by tools/gen/generate.R -- do not edit by hand.

#' AppsV1Api
#'
#' Typed Kubernetes API client for the `AppsV1` surface. See generated methods for available operations.
#' @name AppsV1Api
#' @noMd
#' @export
AppsV1Api <- R6::R6Class(
  "AppsV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getAppsV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1ControllerRevisionForAllNamespaces
    #' list or watch objects of kind ControllerRevision
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_controller_revision_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/controllerrevisions",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ControllerRevisionList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1DaemonSetForAllNamespaces
    #' list or watch objects of kind DaemonSet
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_daemon_set_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/daemonsets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1DaemonSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1DeploymentForAllNamespaces
    #' list or watch objects of kind Deployment
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_deployment_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/deployments",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1DeploymentList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1NamespacedControllerRevision
    #' list or watch objects of kind ControllerRevision
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_controller_revision = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ControllerRevisionList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAppsV1NamespacedControllerRevision
    #' create a ControllerRevision
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_controller_revision = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ControllerRevision",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1CollectionNamespacedControllerRevision
    #' delete collection of ControllerRevision
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_controller_revision = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedControllerRevision
    #' read the specified ControllerRevision
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_controller_revision = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1ControllerRevision",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedControllerRevision
    #' replace the specified ControllerRevision
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_controller_revision = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ControllerRevision",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedControllerRevision
    #' partially update the specified ControllerRevision
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_controller_revision = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ControllerRevision",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1NamespacedControllerRevision
    #' delete a ControllerRevision
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_controller_revision = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1NamespacedDaemonSet
    #' list or watch objects of kind DaemonSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_daemon_set = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1DaemonSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAppsV1NamespacedDaemonSet
    #' create a DaemonSet
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_daemon_set = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1DaemonSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1CollectionNamespacedDaemonSet
    #' delete collection of DaemonSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_daemon_set = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedDaemonSet
    #' read the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_daemon_set = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1DaemonSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedDaemonSet
    #' replace the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_daemon_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1DaemonSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedDaemonSet
    #' partially update the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_daemon_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1DaemonSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1NamespacedDaemonSet
    #' delete a DaemonSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_daemon_set = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedDaemonSetStatus
    #' read status of the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_daemon_set_status = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}/status",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1DaemonSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedDaemonSetStatus
    #' replace status of the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_daemon_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}/status",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1DaemonSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedDaemonSetStatus
    #' partially update status of the specified DaemonSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_daemon_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/daemonsets/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1DaemonSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1NamespacedDeployment
    #' list or watch objects of kind Deployment
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_deployment = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1DeploymentList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAppsV1NamespacedDeployment
    #' create a Deployment
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_deployment = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Deployment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1CollectionNamespacedDeployment
    #' delete collection of Deployment
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_deployment = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedDeployment
    #' read the specified Deployment
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_deployment = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Deployment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedDeployment
    #' replace the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_deployment = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Deployment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedDeployment
    #' partially update the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_deployment = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Deployment",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1NamespacedDeployment
    #' delete a Deployment
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_deployment = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedDeploymentScale
    #' read scale of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_deployment_scale = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedDeploymentScale
    #' replace scale of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_deployment_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedDeploymentScale
    #' partially update scale of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_deployment_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedDeploymentStatus
    #' read status of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_deployment_status = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/status",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Deployment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedDeploymentStatus
    #' replace status of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_deployment_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/status",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Deployment",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedDeploymentStatus
    #' partially update status of the specified Deployment
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_deployment_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/deployments/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Deployment",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1NamespacedReplicaSet
    #' list or watch objects of kind ReplicaSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_replica_set = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ReplicaSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAppsV1NamespacedReplicaSet
    #' create a ReplicaSet
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_replica_set = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ReplicaSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1CollectionNamespacedReplicaSet
    #' delete collection of ReplicaSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_replica_set = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedReplicaSet
    #' read the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_replica_set = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1ReplicaSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedReplicaSet
    #' replace the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_replica_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ReplicaSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedReplicaSet
    #' partially update the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_replica_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ReplicaSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1NamespacedReplicaSet
    #' delete a ReplicaSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_replica_set = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedReplicaSetScale
    #' read scale of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_replica_set_scale = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/scale",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedReplicaSetScale
    #' replace scale of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_replica_set_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/scale",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedReplicaSetScale
    #' partially update scale of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_replica_set_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/scale",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedReplicaSetStatus
    #' read status of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_replica_set_status = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1ReplicaSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedReplicaSetStatus
    #' replace status of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_replica_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ReplicaSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedReplicaSetStatus
    #' partially update status of the specified ReplicaSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_replica_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1ReplicaSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1NamespacedStatefulSet
    #' list or watch objects of kind StatefulSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_namespaced_stateful_set = function(namespace, pretty = NULL, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1StatefulSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createAppsV1NamespacedStatefulSet
    #' create a StatefulSet
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    create_namespaced_stateful_set = function(namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets",
        method = "POST",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StatefulSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1CollectionNamespacedStatefulSet
    #' delete collection of StatefulSet
    #' @param namespace
    #' @param pretty = NULL
    #' @param continue = NULL
    #' @param dry_run = NULL
    #' @param field_selector = NULL
    #' @param grace_period_seconds = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param body = NULL
    delete_collection_namespaced_stateful_set = function(namespace, pretty = NULL, continue = NULL, dry_run = NULL, field_selector = NULL, grace_period_seconds = NULL, label_selector = NULL, limit = NULL, orphan_dependents = NULL, propagation_policy = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets",
        method = "DELETE",
        path_params = list(`namespace` = namespace),
        query_params = list(`pretty` = pretty, `continue` = continue, `dryRun` = dry_run, `fieldSelector` = field_selector, `gracePeriodSeconds` = grace_period_seconds, `labelSelector` = label_selector, `limit` = limit, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedStatefulSet
    #' read the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_stateful_set = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1StatefulSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedStatefulSet
    #' replace the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_stateful_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StatefulSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedStatefulSet
    #' partially update the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_stateful_set = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StatefulSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' deleteAppsV1NamespacedStatefulSet
    #' delete a StatefulSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param grace_period_seconds = NULL
    #' @param orphan_dependents = NULL
    #' @param propagation_policy = NULL
    #' @param body = NULL
    delete_namespaced_stateful_set = function(name, namespace, pretty = NULL, dry_run = NULL, grace_period_seconds = NULL, orphan_dependents = NULL, propagation_policy = NULL, body = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}",
        method = "DELETE",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `gracePeriodSeconds` = grace_period_seconds, `orphanDependents` = orphan_dependents, `propagationPolicy` = propagation_policy),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedStatefulSetScale
    #' read scale of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_stateful_set_scale = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/scale",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedStatefulSetScale
    #' replace scale of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_stateful_set_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/scale",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedStatefulSetScale
    #' partially update scale of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_stateful_set_scale = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/scale",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1Scale",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' readAppsV1NamespacedStatefulSetStatus
    #' read status of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param pretty = NULL
    read_namespaced_stateful_set_status = function(name, namespace, pretty = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty),
        header_params = list(),
        body = NULL,
        response_type = "V1StatefulSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceAppsV1NamespacedStatefulSetStatus
    #' replace status of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    replace_namespaced_stateful_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status",
        method = "PUT",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StatefulSet",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchAppsV1NamespacedStatefulSetStatus
    #' partially update status of the specified StatefulSet
    #' @param name
    #' @param namespace
    #' @param body
    #' @param pretty = NULL
    #' @param dry_run = NULL
    #' @param field_manager = NULL
    #' @param field_validation = NULL
    #' @param force = NULL
    #' @param content_type = "application/json-patch+json"
    patch_namespaced_stateful_set_status = function(name, namespace, body, pretty = NULL, dry_run = NULL, field_manager = NULL, field_validation = NULL, force = NULL, content_type = "application/json-patch+json") {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`pretty` = pretty, `dryRun` = dry_run, `fieldManager` = field_manager, `fieldValidation` = field_validation, `force` = force),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1StatefulSet",
        content_type = content_type,
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1ReplicaSetForAllNamespaces
    #' list or watch objects of kind ReplicaSet
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_replica_set_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/replicasets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1ReplicaSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' listAppsV1StatefulSetForAllNamespaces
    #' list or watch objects of kind StatefulSet
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    list_stateful_set_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/statefulsets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1StatefulSetList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1ControllerRevisionListForAllNamespaces
    #' watch individual changes to a list of ControllerRevision. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_controller_revision_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/controllerrevisions",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1DaemonSetListForAllNamespaces
    #' watch individual changes to a list of DaemonSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_daemon_set_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/daemonsets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1DeploymentListForAllNamespaces
    #' watch individual changes to a list of Deployment. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_deployment_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/deployments",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedControllerRevisionList
    #' watch individual changes to a list of ControllerRevision. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_controller_revision_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/controllerrevisions",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedControllerRevision
    #' watch changes to an object of kind ControllerRevision. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_controller_revision = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/controllerrevisions/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedDaemonSetList
    #' watch individual changes to a list of DaemonSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_daemon_set_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/daemonsets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedDaemonSet
    #' watch changes to an object of kind DaemonSet. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_daemon_set = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/daemonsets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedDeploymentList
    #' watch individual changes to a list of Deployment. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_deployment_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/deployments",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedDeployment
    #' watch changes to an object of kind Deployment. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_deployment = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/deployments/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedReplicaSetList
    #' watch individual changes to a list of ReplicaSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_replica_set_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/replicasets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedReplicaSet
    #' watch changes to an object of kind ReplicaSet. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_replica_set = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/replicasets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedStatefulSetList
    #' watch individual changes to a list of StatefulSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_stateful_set_list = function(namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/statefulsets",
        method = "GET",
        path_params = list(`namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1NamespacedStatefulSet
    #' watch changes to an object of kind StatefulSet. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    #' @param namespace
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_namespaced_stateful_set = function(name, namespace, allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/namespaces/{namespace}/statefulsets/{name}",
        method = "GET",
        path_params = list(`name` = name, `namespace` = namespace),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1ReplicaSetListForAllNamespaces
    #' watch individual changes to a list of ReplicaSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_replica_set_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/replicasets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchAppsV1StatefulSetListForAllNamespaces
    #' watch individual changes to a list of StatefulSet. deprecated: use the 'watch' parameter with a list operation instead.
    #' @param allow_watch_bookmarks = NULL
    #' @param continue = NULL
    #' @param field_selector = NULL
    #' @param label_selector = NULL
    #' @param limit = NULL
    #' @param pretty = NULL
    #' @param resource_version = NULL
    #' @param resource_version_match = NULL
    #' @param send_initial_events = NULL
    #' @param timeout_seconds = NULL
    #' @param watch = NULL
    watch_stateful_set_list_for_all_namespaces = function(allow_watch_bookmarks = NULL, continue = NULL, field_selector = NULL, label_selector = NULL, limit = NULL, pretty = NULL, resource_version = NULL, resource_version_match = NULL, send_initial_events = NULL, timeout_seconds = NULL, watch = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apps/v1/watch/statefulsets",
        method = "GET",
        path_params = list(),
        query_params = list(`allowWatchBookmarks` = allow_watch_bookmarks, `continue` = continue, `fieldSelector` = field_selector, `labelSelector` = label_selector, `limit` = limit, `pretty` = pretty, `resourceVersion` = resource_version, `resourceVersionMatch` = resource_version_match, `sendInitialEvents` = send_initial_events, `timeoutSeconds` = timeout_seconds, `watch` = watch),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

