# Generated by tools/gen/generate.R -- do not edit by hand.

#' V2PodsMetricSource
#'
#' PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
#' @name V2PodsMetricSource
#' @noMd
#' @export
V2PodsMetricSource <- R6::R6Class(
  "V2PodsMetricSource",
  public = list(
    `metric` = NULL,
    `target` = NULL
    ,
    #' @description Construct.
    initialize = function(`metric` = NULL, `target` = NULL) {
      self$`metric` <- `metric`
      self$`target` <- `target`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["metric"]] <- if (!is.null(self$`metric`)) self$`metric`$to_list() else NULL
      out[["target"]] <- if (!is.null(self$`target`)) self$`target`$to_list() else NULL
      drop_nulls_deep(out)
    }
  )
)

V2PodsMetricSource$from_list <- function(x) {
  V2PodsMetricSource$new(
    `metric` = if (is.null(x[["metric"]])) NULL else V2MetricIdentifier$from_list(x[["metric"]]),
    `target` = if (is.null(x[["target"]])) NULL else V2MetricTarget$from_list(x[["target"]])
  )
}

V2PodsMetricSource$required_fields <- c("metric", "target")

