# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1CSIDriverSpec
#'
#' CSIDriverSpec is the specification of a CSIDriver.
#' @name V1CSIDriverSpec
#' @noMd
#' @export
V1CSIDriverSpec <- R6::R6Class(
  "V1CSIDriverSpec",
  public = list(
    `attach_required` = NULL,
    `fs_group_policy` = NULL,
    `pod_info_on_mount` = NULL,
    `requires_republish` = NULL,
    `se_linux_mount` = NULL,
    `storage_capacity` = NULL,
    `token_requests` = NULL,
    `volume_lifecycle_modes` = NULL
    ,
    #' @description Construct.
    initialize = function(`attach_required` = NULL, `fs_group_policy` = NULL, `pod_info_on_mount` = NULL, `requires_republish` = NULL, `se_linux_mount` = NULL, `storage_capacity` = NULL, `token_requests` = NULL, `volume_lifecycle_modes` = NULL) {
      self$`attach_required` <- `attach_required`
      self$`fs_group_policy` <- `fs_group_policy`
      self$`pod_info_on_mount` <- `pod_info_on_mount`
      self$`requires_republish` <- `requires_republish`
      self$`se_linux_mount` <- `se_linux_mount`
      self$`storage_capacity` <- `storage_capacity`
      self$`token_requests` <- `token_requests`
      self$`volume_lifecycle_modes` <- `volume_lifecycle_modes`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["attachRequired"]] <- self$`attach_required`
      out[["fsGroupPolicy"]] <- self$`fs_group_policy`
      out[["podInfoOnMount"]] <- self$`pod_info_on_mount`
      out[["requiresRepublish"]] <- self$`requires_republish`
      out[["seLinuxMount"]] <- self$`se_linux_mount`
      out[["storageCapacity"]] <- self$`storage_capacity`
      out[["tokenRequests"]] <- if (!is.null(self$`token_requests`)) lapply(self$`token_requests`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["volumeLifecycleModes"]] <- self$`volume_lifecycle_modes`
      drop_nulls_deep(out)
    }
  )
)

V1CSIDriverSpec$from_list <- function(x) {
  V1CSIDriverSpec$new(
    `attach_required` = x[["attachRequired"]],
    `fs_group_policy` = x[["fsGroupPolicy"]],
    `pod_info_on_mount` = x[["podInfoOnMount"]],
    `requires_republish` = x[["requiresRepublish"]],
    `se_linux_mount` = x[["seLinuxMount"]],
    `storage_capacity` = x[["storageCapacity"]],
    `token_requests` = if (is.null(x[["tokenRequests"]])) NULL else lapply(x[["tokenRequests"]], StorageV1TokenRequest$from_list),
    `volume_lifecycle_modes` = x[["volumeLifecycleModes"]]
  )
}

