# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ScopedResourceSelectorRequirement
#'
#' A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.
#' @name V1ScopedResourceSelectorRequirement
#' @noMd
#' @export
V1ScopedResourceSelectorRequirement <- R6::R6Class(
  "V1ScopedResourceSelectorRequirement",
  public = list(
    `operator` = NULL,
    `scope_name` = NULL,
    `values` = NULL
    ,
    #' @description Construct.
    initialize = function(`operator` = NULL, `scope_name` = NULL, `values` = NULL) {
      self$`operator` <- `operator`
      self$`scope_name` <- `scope_name`
      self$`values` <- `values`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["operator"]] <- self$`operator`
      out[["scopeName"]] <- self$`scope_name`
      out[["values"]] <- self$`values`
      drop_nulls_deep(out)
    }
  )
)

V1ScopedResourceSelectorRequirement$from_list <- function(x) {
  V1ScopedResourceSelectorRequirement$new(
    `operator` = x[["operator"]],
    `scope_name` = x[["scopeName"]],
    `values` = x[["values"]]
  )
}

V1ScopedResourceSelectorRequirement$required_fields <- c("scopeName", "operator")

