# Generated by tools/gen/generate.R -- do not edit by hand.

#' ApiextensionsV1Api
#'
#' Typed Kubernetes API client for the `ApiextensionsV1` surface. See generated methods for available operations.
#' @name ApiextensionsV1Api
#' @noMd
#' @export
ApiextensionsV1Api <- R6::R6Class(
  "ApiextensionsV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getApiextensionsV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listApiextensionsV1CustomResourceDefinition
    #' list or watch objects of kind CustomResourceDefinition
    list_custom_resource_definition = function() {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinitionList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createApiextensionsV1CustomResourceDefinition
    #' create a CustomResourceDefinition
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_custom_resource_definition = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteApiextensionsV1CollectionCustomResourceDefinition
    #' delete collection of CustomResourceDefinition
    #' @param dry_run = NULL
    delete_collection_custom_resource_definition = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readApiextensionsV1CustomResourceDefinition
    #' read the specified CustomResourceDefinition
    #' @param name
    read_custom_resource_definition = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceApiextensionsV1CustomResourceDefinition
    #' replace the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_custom_resource_definition = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchApiextensionsV1CustomResourceDefinition
    #' partially update the specified CustomResourceDefinition
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_custom_resource_definition = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteApiextensionsV1CustomResourceDefinition
    #' delete a CustomResourceDefinition
    #' @param name
    #' @param dry_run = NULL
    delete_custom_resource_definition = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readApiextensionsV1CustomResourceDefinitionStatus
    #' read status of the specified CustomResourceDefinition
    #' @param name
    read_custom_resource_definition_status = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceApiextensionsV1CustomResourceDefinitionStatus
    #' replace status of the specified CustomResourceDefinition
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_custom_resource_definition_status = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1CustomResourceDefinition",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchApiextensionsV1CustomResourceDefinitionStatus
    #' partially update status of the specified CustomResourceDefinition
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_custom_resource_definition_status = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1CustomResourceDefinition",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' watchApiextensionsV1CustomResourceDefinitionList
    #' watch individual changes to a list of CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead.
    watch_custom_resource_definition_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchApiextensionsV1CustomResourceDefinition
    #' watch changes to an object of kind CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_custom_resource_definition = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

