# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1PodAntiAffinity
#'
#' Pod anti affinity is a group of inter pod anti affinity scheduling rules.
#' @name V1PodAntiAffinity
#' @noMd
#' @export
V1PodAntiAffinity <- R6::R6Class(
  "V1PodAntiAffinity",
  public = list(
    `preferred_during_scheduling_ignored_during_execution` = NULL,
    `required_during_scheduling_ignored_during_execution` = NULL
    ,
    #' @description Construct.
    initialize = function(`preferred_during_scheduling_ignored_during_execution` = NULL, `required_during_scheduling_ignored_during_execution` = NULL) {
      self$`preferred_during_scheduling_ignored_during_execution` <- `preferred_during_scheduling_ignored_during_execution`
      self$`required_during_scheduling_ignored_during_execution` <- `required_during_scheduling_ignored_during_execution`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["preferredDuringSchedulingIgnoredDuringExecution"]] <- if (!is.null(self$`preferred_during_scheduling_ignored_during_execution`)) lapply(self$`preferred_during_scheduling_ignored_during_execution`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["requiredDuringSchedulingIgnoredDuringExecution"]] <- if (!is.null(self$`required_during_scheduling_ignored_during_execution`)) lapply(self$`required_during_scheduling_ignored_during_execution`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1PodAntiAffinity$from_list <- function(x) {
  V1PodAntiAffinity$new(
    `preferred_during_scheduling_ignored_during_execution` = if (is.null(x[["preferredDuringSchedulingIgnoredDuringExecution"]])) NULL else lapply(x[["preferredDuringSchedulingIgnoredDuringExecution"]], V1WeightedPodAffinityTerm$from_list),
    `required_during_scheduling_ignored_during_execution` = if (is.null(x[["requiredDuringSchedulingIgnoredDuringExecution"]])) NULL else lapply(x[["requiredDuringSchedulingIgnoredDuringExecution"]], V1PodAffinityTerm$from_list)
  )
}

