# Generated by tools/gen/generate.R -- do not edit by hand.

#' NodeV1Api
#'
#' Typed Kubernetes API client for the `NodeV1` surface. See generated methods for available operations.
#' @name NodeV1Api
#' @noMd
#' @export
NodeV1Api <- R6::R6Class(
  "NodeV1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getNodeV1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listNodeV1RuntimeClass
    #' list or watch objects of kind RuntimeClass
    list_runtime_class = function() {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1RuntimeClassList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createNodeV1RuntimeClass
    #' create a RuntimeClass
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_runtime_class = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1RuntimeClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteNodeV1CollectionRuntimeClass
    #' delete collection of RuntimeClass
    #' @param dry_run = NULL
    delete_collection_runtime_class = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readNodeV1RuntimeClass
    #' read the specified RuntimeClass
    #' @param name
    read_runtime_class = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1RuntimeClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceNodeV1RuntimeClass
    #' replace the specified RuntimeClass
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_runtime_class = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1RuntimeClass",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchNodeV1RuntimeClass
    #' partially update the specified RuntimeClass
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_runtime_class = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1RuntimeClass",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteNodeV1RuntimeClass
    #' delete a RuntimeClass
    #' @param name
    #' @param dry_run = NULL
    delete_runtime_class = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/runtimeclasses/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchNodeV1RuntimeClassList
    #' watch individual changes to a list of RuntimeClass. deprecated: use the 'watch' parameter with a list operation instead.
    watch_runtime_class_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/watch/runtimeclasses",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchNodeV1RuntimeClass
    #' watch changes to an object of kind RuntimeClass. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_runtime_class = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/node.k8s.io/v1/watch/runtimeclasses/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

