# Generated by tools/gen/generate.R -- do not edit by hand.

#' CertificatesV1alpha1Api
#'
#' Typed Kubernetes API client for the `CertificatesV1alpha1` surface. See generated methods for available operations.
#' @name CertificatesV1alpha1Api
#' @noMd
#' @export
CertificatesV1alpha1Api <- R6::R6Class(
  "CertificatesV1alpha1Api",
  public = list(
    #' @field api_client The backing [ApiClient].
    api_client = NULL,
    #' @description
    #' @param api_client An [ApiClient].
    initialize = function(api_client = ApiClient$new()) {
      self$api_client <- api_client
    }
    ,
    #' getCertificatesV1alpha1APIResources
    #' get available resources
    get_api_resources = function() {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1APIResourceList",
        content_type = "application/json",
        accept = "application/json"
      )
    }
    ,
    #' listCertificatesV1alpha1ClusterTrustBundle
    #' list or watch objects of kind ClusterTrustBundle
    list_cluster_trust_bundle = function() {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1alpha1ClusterTrustBundleList",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' createCertificatesV1alpha1ClusterTrustBundle
    #' create a ClusterTrustBundle
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    create_cluster_trust_bundle = function(body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles",
        method = "POST",
        path_params = list(),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1alpha1ClusterTrustBundle",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' deleteCertificatesV1alpha1CollectionClusterTrustBundle
    #' delete collection of ClusterTrustBundle
    #' @param dry_run = NULL
    delete_collection_cluster_trust_bundle = function(dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles",
        method = "DELETE",
        path_params = list(),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' readCertificatesV1alpha1ClusterTrustBundle
    #' read the specified ClusterTrustBundle
    #' @param name
    read_cluster_trust_bundle = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1alpha1ClusterTrustBundle",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' replaceCertificatesV1alpha1ClusterTrustBundle
    #' replace the specified ClusterTrustBundle
    #' @param name
    #' @param body
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    replace_cluster_trust_bundle = function(name, body, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/{name}",
        method = "PUT",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = if (inherits(body, "R6")) body$to_list() else body,
        response_type = "V1alpha1ClusterTrustBundle",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' patchCertificatesV1alpha1ClusterTrustBundle
    #' partially update the specified ClusterTrustBundle
    #' @param name
    #' @param dry_run = NULL
    #' @param field_validation = NULL
    patch_cluster_trust_bundle = function(name, dry_run = NULL, field_validation = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/{name}",
        method = "PATCH",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run, `fieldValidation` = field_validation),
        header_params = list(),
        body = NULL,
        response_type = "V1alpha1ClusterTrustBundle",
        content_type = "application/json-patch+json",
        accept = "application/json"
      )
    }
    ,
    #' deleteCertificatesV1alpha1ClusterTrustBundle
    #' delete a ClusterTrustBundle
    #' @param name
    #' @param dry_run = NULL
    delete_cluster_trust_bundle = function(name, dry_run = NULL) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/{name}",
        method = "DELETE",
        path_params = list(`name` = name),
        query_params = list(`dryRun` = dry_run),
        header_params = list(),
        body = NULL,
        response_type = "V1Status",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCertificatesV1alpha1ClusterTrustBundleList
    #' watch individual changes to a list of ClusterTrustBundle. deprecated: use the 'watch' parameter with a list operation instead.
    watch_cluster_trust_bundle_list = function() {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/watch/clustertrustbundles",
        method = "GET",
        path_params = list(),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
    ,
    #' watchCertificatesV1alpha1ClusterTrustBundle
    #' watch changes to an object of kind ClusterTrustBundle. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
    #' @param name
    watch_cluster_trust_bundle = function(name) {
      self$api_client$call_api(
        resource_path = "/apis/certificates.k8s.io/v1alpha1/watch/clustertrustbundles/{name}",
        method = "GET",
        path_params = list(`name` = name),
        query_params = list(),
        header_params = list(),
        body = NULL,
        response_type = "V1WatchEvent",
        content_type = "*/*",
        accept = "application/json"
      )
    }
  )
)

