# Generated by tools/gen/generate.R -- do not edit by hand.

#' V1ContainerStatus
#'
#' ContainerStatus contains details for the current status of this container.
#' @name V1ContainerStatus
#' @noMd
#' @export
V1ContainerStatus <- R6::R6Class(
  "V1ContainerStatus",
  public = list(
    `allocated_resources` = NULL,
    `allocated_resources_status` = NULL,
    `container_id` = NULL,
    `image` = NULL,
    `image_id` = NULL,
    `last_state` = NULL,
    `name` = NULL,
    `ready` = NULL,
    `resources` = NULL,
    `restart_count` = NULL,
    `started` = NULL,
    `state` = NULL,
    `user` = NULL,
    `volume_mounts` = NULL
    ,
    #' @description Construct.
    initialize = function(`allocated_resources` = NULL, `allocated_resources_status` = NULL, `container_id` = NULL, `image` = NULL, `image_id` = NULL, `last_state` = NULL, `name` = NULL, `ready` = NULL, `resources` = NULL, `restart_count` = NULL, `started` = NULL, `state` = NULL, `user` = NULL, `volume_mounts` = NULL) {
      self$`allocated_resources` <- `allocated_resources`
      self$`allocated_resources_status` <- `allocated_resources_status`
      self$`container_id` <- `container_id`
      self$`image` <- `image`
      self$`image_id` <- `image_id`
      self$`last_state` <- `last_state`
      self$`name` <- `name`
      self$`ready` <- `ready`
      self$`resources` <- `resources`
      self$`restart_count` <- `restart_count`
      self$`started` <- `started`
      self$`state` <- `state`
      self$`user` <- `user`
      self$`volume_mounts` <- `volume_mounts`
    },

    #' @description Convert to a plain named list (JSON keys).
    to_list = function() {
      out <- list()
      out[["allocatedResources"]] <- if (!is.null(self$`allocated_resources`)) lapply(self$`allocated_resources`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["allocatedResourcesStatus"]] <- if (!is.null(self$`allocated_resources_status`)) lapply(self$`allocated_resources_status`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      out[["containerID"]] <- self$`container_id`
      out[["image"]] <- self$`image`
      out[["imageID"]] <- self$`image_id`
      out[["lastState"]] <- if (!is.null(self$`last_state`)) self$`last_state`$to_list() else NULL
      out[["name"]] <- self$`name`
      out[["ready"]] <- self$`ready`
      out[["resources"]] <- if (!is.null(self$`resources`)) self$`resources`$to_list() else NULL
      out[["restartCount"]] <- self$`restart_count`
      out[["started"]] <- self$`started`
      out[["state"]] <- if (!is.null(self$`state`)) self$`state`$to_list() else NULL
      out[["user"]] <- if (!is.null(self$`user`)) self$`user`$to_list() else NULL
      out[["volumeMounts"]] <- if (!is.null(self$`volume_mounts`)) lapply(self$`volume_mounts`, function(.x) if (is.null(.x)) NULL else .x$to_list()) else NULL
      drop_nulls_deep(out)
    }
  )
)

V1ContainerStatus$from_list <- function(x) {
  V1ContainerStatus$new(
    `allocated_resources` = if (is.null(x[["allocatedResources"]])) NULL else lapply(x[["allocatedResources"]], Quantity$from_list),
    `allocated_resources_status` = if (is.null(x[["allocatedResourcesStatus"]])) NULL else lapply(x[["allocatedResourcesStatus"]], V1ResourceStatus$from_list),
    `container_id` = x[["containerID"]],
    `image` = x[["image"]],
    `image_id` = x[["imageID"]],
    `last_state` = if (is.null(x[["lastState"]])) NULL else V1ContainerState$from_list(x[["lastState"]]),
    `name` = x[["name"]],
    `ready` = x[["ready"]],
    `resources` = if (is.null(x[["resources"]])) NULL else V1ResourceRequirements$from_list(x[["resources"]]),
    `restart_count` = x[["restartCount"]],
    `started` = x[["started"]],
    `state` = if (is.null(x[["state"]])) NULL else V1ContainerState$from_list(x[["state"]]),
    `user` = if (is.null(x[["user"]])) NULL else V1ContainerUser$from_list(x[["user"]]),
    `volume_mounts` = if (is.null(x[["volumeMounts"]])) NULL else lapply(x[["volumeMounts"]], V1VolumeMountStatus$from_list)
  )
}

V1ContainerStatus$required_fields <- c("name", "ready", "restartCount", "image", "imageID")

